"use client";

import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from "react";

export type Language = "ru" | "en" | "be" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const LANGUAGE_STORAGE_KEY = "biznes_language";

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Header
    "nav.catalog": "Каталог",
    "nav.news": "Новости",
    "nav.promotions": "Акции",
    "nav.about": "О проекте",
    "nav.addCompany": "Добавить организацию",
    "nav.favorites": "Избранное",

    // Search
    "search.placeholder": "Название компании или услуга",
    "search.region": "Выбрать регион",
    "search.allRegions": "Все регионы",
    "search.find": "Найти",
    "search.results": "Результаты поиска",
    "search.found": "Найдено",

    // Main page
    "hero.title": "Бизнес-справочник Беларуси",
    "hero.subtitle": "Поиск предприятий, организаций и компаний. Товары и услуги от надёжных партнёров.",
    "stats.companies": "Компаний",
    "stats.categories": "Категорий",
    "stats.regions": "Регионов",

    // Catalog
    "catalog.title": "Каталог по категориям",
    "catalog.subcategories": "Подкатегории",
    "catalog.companies": "Компании",
    "catalog.backToCatalog": "Вернуться в каталог",
    "catalog.backToCategory": "Вернуться к категории",

    // Company
    "company.about": "О компании",
    "company.products": "Продукция",
    "company.services": "Услуги",
    "company.vacancies": "Вакансии",
    "company.gallery": "Фотогалерея",
    "company.workHours": "Время работы",
    "company.contacts": "Контакты",
    "company.phone": "Телефон",
    "company.email": "Email",
    "company.website": "Сайт",
    "company.address": "Адрес",
    "company.call": "Позвонить",
    "company.write": "Написать",
    "company.details": "Подробнее",
    "company.reviews": "отзывов",
    "company.notFound": "Компании не найдены",
    "company.notFoundDesc": "В выбранном регионе нет компаний в этой категории",
    "company.showAllRegions": "Показать все регионы",

    // AI Assistant
    "ai.title": "AI Assistent",
    "ai.description": "Оставьте заявку через AI-ассистента. Он автоматически разошлёт ваш запрос компаниям.",
    "ai.inactive": "AI-ассистент недоступен",
    "ai.personalAssistant": "Ваш персональный помощник",
    "ai.requestSent": "Заявка отправлена!",
    "ai.requestProcessing": "AI-ассистент обработает ваш запрос и разошлёт его подходящим компаниям.",
    "ai.placeholder": "Опишите, что вам нужно найти или заказать...",
    "ai.sendRequest": "Отправить запрос",
    "ai.requestTo": "Запрос в",
    "ai.prioritySent": "Заявка отправлена с приоритетом!",
    "ai.priorityDesc": "Компания получит ваш запрос в первую очередь.",
    "ai.describePlaceholder": "Опишите ваш запрос...",

    // Regions
    "region.minsk": "Минск",
    "region.minsk-region": "Минская область",
    "region.brest": "Брестская область",
    "region.vitebsk": "Витебская область",
    "region.gomel": "Гомельская область",
    "region.grodno": "Гродненская область",
    "region.mogilev": "Могилёвская область",

    // Messages
    "message.title": "Написать сообщение",
    "message.selectChannel": "Выберите способ связи",
    "message.yourMessage": "Ваше сообщение",
    "message.send": "Отправить",

    // News
    "news.title": "Новости",
    "news.readMore": "Читать далее",

    // Footer
    "footer.forBusiness": "Для бизнеса",
    "footer.addCompany": "Добавить компанию",
    "footer.advertising": "Реклама на сайте",
    "footer.tariffs": "Тарифы",
    "footer.catalog": "Каталог",
    "footer.contacts": "Контакты",
    "footer.agreement": "Пользовательское соглашение",
    "footer.offer": "Публичный договор (оферта)",
    "footer.adRequest": "Заявка на размещение рекламы",
    "footer.rights": "Все права защищены",
    "footer.information": "Информация",

    // Add company form
    "addCompany.companyInfo": "Информация о компании",
    "addCompany.contactInfo": "Контактная информация компании",

    // Favorites
    "favorites.title": "Избранное",
    "favorites.empty": "У вас пока нет избранных компаний",
    "favorites.add": "Добавить в избранное",
    "favorites.remove": "Удалить из избранного",

    // Common
    "common.loading": "Загрузка...",
    "common.error": "Ошибка",
    "common.back": "Назад",
    "common.home": "Главная",

    // Categories
    "cat.automobiles": "Автомобили",
    "cat.construction": "Строительство",
    "cat.medicine": "Медицина",
    "cat.education": "Образование",
    "cat.finance": "Финансы",
    "cat.it-telecom": "IT и Телеком",
    "cat.trade": "Торговля",
    "cat.services": "Услуги",
    "cat.transport": "Транспорт",
    "cat.realestate": "Недвижимость",
    "cat.restaurants": "Рестораны и кафе",
    "cat.beauty": "Красота и здоровье",

    // Category descriptions
    "cat.automobiles.desc": "Автосалоны, автосервисы, запчасти",
    "cat.construction.desc": "Строительные компании и материалы",
    "cat.medicine.desc": "Клиники, аптеки, медицинские услуги",
    "cat.education.desc": "Учебные заведения, курсы",
    "cat.finance.desc": "Банки, страхование, инвестиции",
    "cat.it-telecom.desc": "IT-компании, связь, интернет",
    "cat.trade.desc": "Магазины, оптовая торговля",
    "cat.services.desc": "Бытовые и профессиональные услуги",
    "cat.transport.desc": "Грузоперевозки, логистика, такси",
    "cat.realestate.desc": "Агентства, застройщики",
    "cat.restaurants.desc": "Общественное питание",
    "cat.beauty.desc": "Салоны красоты, фитнес, спа",

    // Subcategories - Automobiles
    "subcat.dealers": "Автосалоны",
    "subcat.service": "Автосервис",
    "subcat.parts": "Автозапчасти",
    "subcat.tires": "Шиномонтаж",
    // Subcategories - Construction
    "subcat.companies": "Строительные компании",
    "subcat.materials": "Стройматериалы",
    "subcat.renovation": "Ремонт и отделка",
    "subcat.design": "Проектирование",
    // Subcategories - Medicine
    "subcat.clinics": "Клиники",
    "subcat.pharmacies": "Аптеки",
    "subcat.dental": "Стоматология",
    "subcat.diagnostics": "Диагностика",
    // Subcategories - Education
    "subcat.universities": "Университеты",
    "subcat.courses": "Курсы",
    "subcat.kindergartens": "Детские сады",
    "subcat.schools": "Школы",
    // Subcategories - Finance
    "subcat.banks": "Банки",
    "subcat.insurance": "Страхование",
    "subcat.loans": "Кредитование",
    "subcat.exchange": "Обмен валют",
    // Subcategories - IT
    "subcat.it-companies": "IT-компании",
    "subcat.isp": "Интернет-провайдеры",
    "subcat.software": "Разработка ПО",
    "subcat.repair": "Ремонт техники",
    // Subcategories - Trade
    "subcat.food": "Продукты питания",
    "subcat.clothing": "Одежда и обувь",
    "subcat.electronics": "Электроника",
    "subcat.furniture": "Мебель",
    // Subcategories - Services
    "subcat.legal": "Юридические услуги",
    "subcat.accounting": "Бухгалтерия",
    "subcat.cleaning": "Клининг",
    "subcat.translation": "Переводы",
    // Subcategories - Transport
    "subcat.cargo": "Грузоперевозки",
    "subcat.taxi": "Такси",
    "subcat.rental": "Аренда авто",
    "subcat.logistics": "Логистика",
    // Subcategories - Real Estate
    "subcat.agencies": "Агентства",
    "subcat.developers": "Застройщики",
    "subcat.rent": "Аренда",
    "subcat.commercial": "Коммерческая",
    // Subcategories - Restaurants
    "subcat.restaurants": "Рестораны",
    "subcat.cafes": "Кафе",
    "subcat.fastfood": "Фастфуд",
    "subcat.delivery": "Доставка еды",
    // Subcategories - Beauty
    "subcat.salons": "Салоны красоты",
    "subcat.fitness": "Фитнес-клубы",
    "subcat.spa": "СПА",
    "subcat.barbershops": "Барбершопы",

    // News
    "news.savushkin.name": "Савушкин продукт",
    "news.savushkin.title": "Савушкин продукт расширяет экспорт молочной продукции в Китай",
    "news.savushkin.excerpt": "Брестский молочный комбинат увеличил поставки в страны Азии на 25%. Компания открывает новую линию по производству сыров премиум-класса для экспортных рынков.",
    "news.santabremor.name": "Санта Бремор",
    "news.santabremor.title": "Санта Бремор открывает новый производственный комплекс",
    "news.santabremor.excerpt": "Крупнейший производитель рыбной продукции в Беларуси инвестирует в расширение мощностей. Новый завод позволит увеличить объём производства на 40%.",
    "news.alutech.name": "Алютех",
    "news.alutech.title": "Алютех выходит на рынки Центральной Азии",
    "news.alutech.excerpt": "Производитель алюминиевых профилей и роллетных систем открывает представительства в Казахстане и Узбекистане. Компания планирует удвоить экспорт к 2027 году.",

    // Services section
    "services.title": "Услуги для бизнеса",
    "services.subtitle": "Комплексные решения для развития и автоматизации вашего бизнеса",
    "services.consultation": "Нужна консультация?",
    "services.consultationDesc": "Подберём оптимальное решение для вашего бизнеса",
    "services.contactUs": "Написать нам",

    // News
    "news.corporate": "Новости компаний Беларуси",
    "news.corporateSubtitle": "Актуальные события ведущих предприятий страны",
    "news.goToWebsite": "Перейти на сайт",

    // About section
    "about.convenientSearch": "Удобный поиск",
    "about.convenientSearchDesc": "Находите компании по названию, категории или региону. Умный поиск с подсказками.",
    "about.aiAssistant": "AI-ассистент",
    "about.aiAssistantDesc": "Оставьте заявку через AI-ассистента, и он автоматически разошлёт её подходящим компаниям.",
    "about.directContact": "Прямой контакт",
    "about.directContactDesc": "Связывайтесь с компаниями напрямую через телефон, email, мессенджеры.",
    "about.aiExplanation": "Если вам необходимо приобрести товар или услугу, вы можете оставить заявку через нашего AI-ассистента. Ассистент автоматически разошлёт ваш запрос компаниям и организациям, которые предлагают данный товар или услугу.",
    "about.aiPlatform": "BiznesInfo — это не справочник, а AI-платформа, соединяющая клиентов и бизнес.",
    "about.submitRequest": "отправить заявку",

    // Services categories
    "services.marketing": "Маркетинг и стратегия",
    "services.automation": "Автоматизация бизнеса",
    "services.digital": "Digital-услуги",
    "services.aiIntegrations": "AI и интеграции",
    "services.analysis": "Анализ и стратегия",
    "services.analysisDesc": "Детальный маркетинговый анализ и формирование стратегии роста на основе данных",
    "services.leads": "Привлечение заявок",
    "services.leadsDesc": "Лидогенерация через оптимизированные рекламные каналы",
    "services.processAutomation": "Автоматизация процессов",
    "services.processAutomationDesc": "Снижение нагрузки на команду и повышение конверсии",
    "services.crm": "CRM-системы",
    "services.crmDesc": "Внедрение и настройка систем управления клиентами",
    "services.websites": "Создание сайтов",
    "services.websitesDesc": "Корпоративные сайты, лендинги и интернет-магазины",
    "services.seo": "SEO-продвижение",
    "services.seoDesc": "Оптимизация для поисковых систем Яндекс и Google",
    "services.contextAds": "Контекстная реклама",
    "services.contextAdsDesc": "Реклама в Google, Яндекс, Meta и социальных сетях",
    "services.aiBots": "AI-боты и чат-боты",
    "services.aiBotsDesc": "Умные боты для Telegram, WhatsApp и веб-сайтов",
    "services.integrations": "Интеграции систем",
    "services.integrationsDesc": "Связь между CRM, 1С, сайтами и внешними сервисами",

    // Search suggestions
    "search.category": "Категория",
    "search.section": "Раздел",
    "search.company": "Компания",
    "search.subcategories": "подкатегорий",

    // Work hours days
    "days.weekdays": "Пн-Пт",
    "days.saturday": "Сб",
    "days.sunday": "Вс",
    "days.dayOff": "Выходной",
    "days.roundClock": "Круглосуточно",
    "days.byAppointment": "По записи",

    // Company page UI
    "company.quickActions": "Быстрые действия",
    "company.locationOnMap": "Расположение на карте",
    "company.buildRoute": "Построить маршрут",
    "company.found": "Найдено",

    // Filter labels
    "filter.region": "Регион",

    // Company data - Company 1 (24pds)
    "company.1.name": "24pds СТО ПроДизельСервис",
    "company.1.address": "Минск, Бетонный проезд, 19А",
    "company.1.description": "Ремонт автоэлектрики, ТНВД, подвески и шиномонтаж",
    "company.1.about": "СТО ПроДизельСервис — это профессиональный автосервис с многолетним опытом работы. Мы специализируемся на ремонте дизельных двигателей, топливной аппаратуры и автоэлектрики. Наши специалисты используют современное диагностическое оборудование.",
    "company.1.services": "Ремонт ТНВД, Ремонт форсунок, Диагностика двигателя, Ремонт автоэлектрики, Шиномонтаж, Ремонт подвески",
    "company.1.products": "Запчасти для дизельных двигателей, Топливные форсунки, Фильтры",

    // Company 33 (МедЦентр Плюс)
    "company.33.name": "МедЦентр Плюс",
    "company.33.address": "Минск, ул. Сурганова, 47Б",
    "company.33.description": "Многопрофильный медицинский центр",
    "company.33.about": "МедЦентр Плюс — современная многопрофильная клиника в центре Минска. Приём ведут врачи высшей категории. Собственная лаборатория и диагностическое оборудование.",
    "company.33.services": "Терапия, Кардиология, Неврология, Гинекология, Урология, УЗИ, Лабораторные анализы",

    // Company 45 (IT Solutions)
    "company.45.name": "IT Solutions",
    "company.45.address": "Минск, ул. Купревича, 1/1",
    "company.45.description": "Разработка программного обеспечения",
    "company.45.about": "IT Solutions — компания по разработке программного обеспечения. Создаём веб-приложения, мобильные приложения, корпоративные системы.",
    "company.45.services": "Веб-разработка, Мобильные приложения, ERP-системы, CRM, Техподдержка",

    // Companies 2-20
    "company.2.name": "Тракинтерсервис ООО",
    "company.2.address": "Минский р-н, пос. Привольный, ул. Мира, 14/40",
    "company.2.description": "Ремонт грузовых и легковых автомобилей, тягачей и прицепов",
    "company.3.name": "Автоцентр PRO-WE",
    "company.3.address": "Брестский р-н, д. Черни, ул. Зеленая, 49",
    "company.3.description": "3D развал-схождение легковых и грузовых автомобилей",
    "company.4.name": "Аирсервис ЧУП",
    "company.4.address": "Минский р-н, пос. Привольный, ул. Мира, 12",
    "company.4.description": "СТО по ремонту грузовой и специальной техники",
    "company.5.name": "Веставто СП ОАО",
    "company.5.address": "Брест, ул. Коммерческая, 17",
    "company.5.description": "Ремонт грузовых автомобилей, шиномонтаж",
    "company.6.name": "АвтоМастер Плюс",
    "company.6.address": "Минск, ул. Притыцкого, 62",
    "company.6.description": "Полный спектр услуг по ремонту легковых автомобилей",
    "company.7.name": "СТО Профи Гомель",
    "company.7.address": "Гомель, ул. Советская, 78",
    "company.7.description": "Диагностика, ремонт двигателей, ходовой части",
    "company.8.name": "Автосервис Европа",
    "company.8.address": "Витебск, пр. Московский, 25",
    "company.8.description": "Специализированный сервис для европейских автомобилей",
    "company.9.name": "Региональный центр ЯМЗ",
    "company.9.address": "Минск, ул. Бабушкина, 21",
    "company.9.description": "Ремонт двигателей ЯМЗ, диагностика",
    "company.10.name": "Гродно-Авто Сервис",
    "company.10.address": "Гродно, ул. Горького, 91",
    "company.10.description": "Комплексный ремонт автомобилей всех марок",
    "company.11.name": "Могилёв АвтоТехЦентр",
    "company.11.address": "Могилёв, ул. Челюскинцев, 45",
    "company.11.description": "Кузовной ремонт, покраска, полировка",
    "company.12.name": "БелДизельСервис",
    "company.12.address": "Минск, ул. Радиальная, 15",
    "company.12.description": "Ремонт дизельных двигателей и топливной аппаратуры",
    "company.13.name": "АвтоДеталь",
    "company.13.address": "Минск, ул. Долгобродская, 24",
    "company.13.description": "Запчасти для легковых автомобилей всех марок",
    "company.14.name": "Грузовые Запчасти БЕЛ",
    "company.14.address": "Минск, ул. Казинца, 86",
    "company.14.description": "Запчасти для грузовых автомобилей МАЗ, КАМАЗ",
    "company.15.name": "Автомир Брест",
    "company.15.address": "Брест, ул. Московская, 332",
    "company.15.description": "Автозапчасти оптом и в розницу",
    "company.16.name": "Запчасти Плюс Гомель",
    "company.16.address": "Гомель, ул. Барыкина, 150",
    "company.16.description": "Оригинальные и неоригинальные запчасти",
    "company.17.name": "ВитАвтоЗап",
    "company.17.address": "Витебск, пр. Строителей, 18",
    "company.17.description": "Запчасти для иномарок, доставка по области",
    "company.18.name": "ШинСервис 24",
    "company.18.address": "Минск, ул. Тимирязева, 67",
    "company.18.description": "Круглосуточный шиномонтаж, хранение шин",
    "company.19.name": "Колесо Брест",
    "company.19.address": "Брест, ул. Гоголя, 78",
    "company.19.description": "Шиномонтаж, балансировка, ремонт дисков",
    "company.20.name": "ШинаГомель",
    "company.20.address": "Гомель, ул. Советская, 136",
    "company.20.description": "Продажа и монтаж шин всех размеров",

    // Companies 21-32 (Construction)
    "company.21.name": "СтройМинск ООО",
    "company.21.address": "Минск, ул. Кальварийская, 25",
    "company.21.description": "Строительство жилых и коммерческих объектов под ключ",
    "company.22.name": "БрестСтрой",
    "company.22.address": "Брест, ул. Ленина, 45",
    "company.22.description": "Строительные работы любой сложности",
    "company.23.name": "ГомельЖилСтрой",
    "company.23.address": "Гомель, пр. Ленина, 55",
    "company.23.description": "Строительство многоквартирных домов",
    "company.24.name": "Витебскстрой",
    "company.24.address": "Витебск, ул. Замковая, 20",
    "company.24.description": "Генеральный подрядчик строительства",
    "company.25.name": "ГродноПромСтрой",
    "company.25.address": "Гродно, ул. Советская, 18",
    "company.25.description": "Промышленное и гражданское строительство",
    "company.26.name": "МогилёвСтройИнвест",
    "company.26.address": "Могилёв, ул. Первомайская, 75",
    "company.26.description": "Инвестиционное строительство",
    "company.27.name": "СтройМатериалы БЕЛ",
    "company.27.address": "Минск, ул. Казинца, 120",
    "company.27.description": "Оптовая продажа стройматериалов",
    "company.28.name": "Керамин-Брест",
    "company.28.address": "Брест, ул. Московская, 275",
    "company.28.description": "Керамическая плитка, сантехника",
    "company.29.name": "Стройбаза Гомель",
    "company.29.address": "Гомель, ул. Барыкина, 200",
    "company.29.description": "Все для строительства и ремонта",
    "company.30.name": "РемонтПлюс",
    "company.30.address": "Минск, ул. Сурганова, 57А",
    "company.30.description": "Ремонт квартир под ключ",
    "company.31.name": "ГомельРемонт",
    "company.31.address": "Гомель, пр. Ленина, 100",
    "company.31.description": "Ремонт квартир и офисов",
    "company.32.name": "ЕвроРемонт Витебск",
    "company.32.address": "Витебск, ул. Ленина, 45",
    "company.32.description": "Качественный ремонт любой сложности",

    // Companies 34-44 (Medicine)
    "company.34.name": "Клиника Лодэ",
    "company.34.address": "Минск, ул. Притыцкого, 140",
    "company.34.description": "Частная медицинская клиника",
    "company.35.name": "Медицинский центр Брест",
    "company.35.address": "Брест, ул. Советская, 67",
    "company.35.description": "Диагностика и лечение",
    "company.36.name": "ГомельМед",
    "company.36.address": "Гомель, ул. Советская, 45",
    "company.36.description": "Современный медицинский центр",
    "company.37.name": "Витебский медцентр",
    "company.37.address": "Витебск, пр. Фрунзе, 80",
    "company.37.description": "Широкий спектр медицинских услуг",
    "company.38.name": "Стоматология 32",
    "company.38.address": "Минск, ул. Немига, 38",
    "company.38.description": "Современная стоматологическая клиника",
    "company.39.name": "ДентаВита",
    "company.39.address": "Минск, ул. Скрыганова, 14",
    "company.39.description": "Имплантация, протезирование, лечение",
    "company.40.name": "Стоматология Улыбка",
    "company.40.address": "Витебск, ул. Замковая, 12",
    "company.40.description": "Стоматологические услуги для всей семьи",
    "company.41.name": "Дентал-Брест",
    "company.41.address": "Брест, ул. Гоголя, 55",
    "company.41.description": "Лечение, протезирование, ортодонтия",
    "company.42.name": "Аптека Первая Помощь",
    "company.42.address": "Минск, пр. Независимости, 58",
    "company.42.description": "Широкий ассортимент лекарств",
    "company.43.name": "Аптека Здоровье",
    "company.43.address": "Гродно, ул. Советская, 5",
    "company.43.description": "Лекарства и медицинские товары",
    "company.44.name": "Фармация Гомель",
    "company.44.address": "Гомель, ул. Советская, 97",
    "company.44.description": "Аптека с доставкой на дом",

    // Companies 46-55 (IT, Trade)
    "company.46.name": "WebDev Гродно",
    "company.46.address": "Гродно, ул. Горького, 87",
    "company.46.description": "Создание сайтов и веб-приложений",
    "company.47.name": "SoftMinsk",
    "company.47.address": "Минск, ул. Тимирязева, 72",
    "company.47.description": "Разработка мобильных приложений",
    "company.48.name": "IT-Сервис Брест",
    "company.48.address": "Брест, ул. Советская, 100",
    "company.48.description": "Ремонт компьютеров и ноутбуков",
    "company.49.name": "КомпМастер",
    "company.49.address": "Минск, ул. Немига, 12",
    "company.49.description": "Срочный ремонт техники",
    "company.50.name": "ЭлектроМир",
    "company.50.address": "Минск, пр. Независимости, 150",
    "company.50.description": "Бытовая техника и электроника",
    "company.51.name": "ТехноПлюс",
    "company.51.address": "Гомель, ул. Советская, 1",
    "company.51.description": "Компьютеры, телефоны, аксессуары",
    "company.52.name": "Мебельный Дом",
    "company.52.address": "Могилёв, ул. Первомайская, 25",
    "company.52.description": "Мебель для дома и офиса",
    "company.53.name": "МебельГрад",
    "company.53.address": "Минск, ул. Уручская, 19",
    "company.53.description": "Мебель белорусских производителей",
    "company.54.name": "Мода и Стиль",
    "company.54.address": "Минск, ул. Немига, 3",
    "company.54.description": "Брендовая одежда и обувь",
    "company.55.name": "Одежда Брест",
    "company.55.address": "Брест, ул. Советская, 65",
    "company.55.description": "Одежда для всей семьи",

    // Companies 56-77 (Restaurants, Beauty, Services, Transport, Real Estate)
    "company.56.name": "Ресторан Минск",
    "company.56.address": "Минск, пр. Победителей, 17",
    "company.56.description": "Белорусская и европейская кухня",
    "company.57.name": "Камяница",
    "company.57.address": "Минск, пл. Свободы, 3",
    "company.57.description": "Традиционная белорусская кухня",
    "company.58.name": "Ресторан Брест",
    "company.58.address": "Брест, ул. Советская, 49",
    "company.58.description": "Европейская кухня, банкеты",
    "company.59.name": "Кафе Уют",
    "company.59.address": "Брест, ул. Советская, 50",
    "company.59.description": "Уютное кафе с домашней кухней",
    "company.60.name": "Кофейня Гомель",
    "company.60.address": "Гомель, пр. Ленина, 18",
    "company.60.description": "Кофе, десерты, завтраки",
    "company.61.name": "Пиццерия Италия",
    "company.61.address": "Минск, ул. Сурганова, 27",
    "company.61.description": "Итальянская пицца, доставка",
    "company.62.name": "Салон Красоты Эстетика",
    "company.62.address": "Минск, ул. Немига, 40",
    "company.62.description": "Полный спектр косметических услуг",
    "company.63.name": "Студия Красоты Bravo",
    "company.63.address": "Минск, ул. Притыцкого, 83",
    "company.63.description": "Маникюр, педикюр, парикмахерские услуги",
    "company.64.name": "Салон Виктория",
    "company.64.address": "Брест, ул. Советская, 78",
    "company.64.description": "Стрижки, окрашивание, уход",
    "company.65.name": "Фитнес-клуб Энергия",
    "company.65.address": "Минск, ул. Притыцкого, 156",
    "company.65.description": "Тренажерный зал, групповые занятия",
    "company.66.name": "СПА-центр Релакс",
    "company.66.address": "Минск, ул. Сурганова, 5А",
    "company.66.description": "Массаж, сауна, косметология",
    "company.67.name": "Барбершоп TOPGUN",
    "company.67.address": "Минск, ул. Зыбицкая, 6",
    "company.67.description": "Мужские стрижки и уход за бородой",
    "company.68.name": "Юридическая фирма Право",
    "company.68.address": "Минск, пр. Независимости, 72",
    "company.68.description": "Юридические консультации и представительство",
    "company.69.name": "Адвокатское бюро Брест",
    "company.69.address": "Брест, ул. Ленина, 31",
    "company.69.description": "Адвокатские услуги",
    "company.70.name": "БухУчёт Сервис",
    "company.70.address": "Минск, ул. Толбухина, 2",
    "company.70.description": "Бухгалтерские услуги для бизнеса",
    "company.71.name": "Клининг Профи",
    "company.71.address": "Минск, ул. Казинца, 52",
    "company.71.description": "Уборка квартир, офисов, коттеджей",
    "company.72.name": "БелГрузПеревозки",
    "company.72.address": "Минск, ул. Радиальная, 40А",
    "company.72.description": "Грузоперевозки по Беларуси и СНГ",
    "company.73.name": "Такси Минск 135",
    "company.73.address": "Минск",
    "company.73.description": "Такси по Минску и области",
    "company.74.name": "АвтоПрокат",
    "company.74.address": "Минск, ул. Притыцкого, 60",
    "company.74.description": "Аренда автомобилей без водителя",
    "company.75.name": "Агентство Твой Дом",
    "company.75.address": "Минск, пр. Независимости, 95",
    "company.75.description": "Покупка, продажа, аренда недвижимости",
    "company.76.name": "А-100 Девелопмент",
    "company.76.address": "Минск, ул. Кирова, 8",
    "company.76.description": "Строительство жилых комплексов",
    "company.77.name": "Аренда Офисов БЦ",
    "company.77.address": "Минск, ул. Сурганова, 61",
    "company.77.description": "Коммерческая недвижимость",
  },

  en: {
    // Header
    "nav.catalog": "Catalog",
    "nav.news": "News",
    "nav.promotions": "Promotions",
    "nav.about": "About",
    "nav.addCompany": "Add organization",
    "nav.favorites": "Favorites",

    // Search
    "search.placeholder": "Company name or service",
    "search.region": "Select region",
    "search.allRegions": "All regions",
    "search.find": "Search",
    "search.results": "Search Results",
    "search.found": "Found",

    // Main page
    "hero.title": "Belarus Business Directory",
    "hero.subtitle": "Search for enterprises, organizations and companies. Goods and services from trusted partners.",
    "stats.companies": "Companies",
    "stats.categories": "Categories",
    "stats.regions": "Regions",

    // Catalog
    "catalog.title": "Catalog by categories",
    "catalog.subcategories": "Subcategories",
    "catalog.companies": "Companies",
    "catalog.backToCatalog": "Back to catalog",
    "catalog.backToCategory": "Back to category",

    // Company
    "company.about": "About company",
    "company.products": "Products",
    "company.services": "Services",
    "company.vacancies": "Vacancies",
    "company.gallery": "Photo gallery",
    "company.workHours": "Working hours",
    "company.contacts": "Contacts",
    "company.phone": "Phone",
    "company.email": "Email",
    "company.website": "Website",
    "company.address": "Address",
    "company.call": "Call",
    "company.write": "Write",
    "company.details": "Details",
    "company.reviews": "reviews",
    "company.notFound": "No companies found",
    "company.notFoundDesc": "There are no companies in this category in the selected region",
    "company.showAllRegions": "Show all regions",

    // AI Assistant
    "ai.title": "AI Assistent",
    "ai.description": "Leave a request through AI assistant. It will automatically send your request to companies.",
    "ai.inactive": "AI assistant unavailable",
    "ai.personalAssistant": "Your personal assistant",
    "ai.requestSent": "Request sent!",
    "ai.requestProcessing": "AI assistant will process your request and send it to suitable companies.",
    "ai.placeholder": "Describe what you need to find or order...",
    "ai.sendRequest": "Send request",
    "ai.requestTo": "Request to",
    "ai.prioritySent": "Request sent with priority!",
    "ai.priorityDesc": "The company will receive your request first.",
    "ai.describePlaceholder": "Describe your request...",

    // Regions
    "region.minsk": "Minsk",
    "region.minsk-region": "Minsk Region",
    "region.brest": "Brest Region",
    "region.vitebsk": "Vitebsk Region",
    "region.gomel": "Gomel Region",
    "region.grodno": "Grodno Region",
    "region.mogilev": "Mogilev Region",

    // Messages
    "message.title": "Send message",
    "message.selectChannel": "Select communication method",
    "message.yourMessage": "Your message",
    "message.send": "Send",

    // News
    "news.title": "News",
    "news.readMore": "Read more",

    // Footer
    "footer.forBusiness": "For business",
    "footer.addCompany": "Add company",
    "footer.advertising": "Advertising",
    "footer.tariffs": "Tariffs",
    "footer.catalog": "Catalog",
    "footer.contacts": "Contacts",
    "footer.agreement": "User agreement",
    "footer.offer": "Public offer",
    "footer.adRequest": "Advertising request",
    "footer.rights": "All rights reserved",
    "footer.information": "Information",

    // Add company form
    "addCompany.companyInfo": "Company Information",
    "addCompany.contactInfo": "Company Contact Information",

    // Favorites
    "favorites.title": "Favorites",
    "favorites.empty": "You have no favorite companies yet",
    "favorites.add": "Add to favorites",
    "favorites.remove": "Remove from favorites",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.back": "Back",
    "common.home": "Home",

    // Categories
    "cat.automobiles": "Automobiles",
    "cat.construction": "Construction",
    "cat.medicine": "Medicine",
    "cat.education": "Education",
    "cat.finance": "Finance",
    "cat.it-telecom": "IT & Telecom",
    "cat.trade": "Trade",
    "cat.services": "Services",
    "cat.transport": "Transport",
    "cat.realestate": "Real Estate",
    "cat.restaurants": "Restaurants & Cafes",
    "cat.beauty": "Beauty & Health",

    // Category descriptions
    "cat.automobiles.desc": "Car dealerships, auto services, spare parts",
    "cat.construction.desc": "Construction companies and materials",
    "cat.medicine.desc": "Clinics, pharmacies, medical services",
    "cat.education.desc": "Educational institutions, courses",
    "cat.finance.desc": "Banks, insurance, investments",
    "cat.it-telecom.desc": "IT companies, communications, internet",
    "cat.trade.desc": "Stores, wholesale trade",
    "cat.services.desc": "Household and professional services",
    "cat.transport.desc": "Freight, logistics, taxi",
    "cat.realestate.desc": "Agencies, developers",
    "cat.restaurants.desc": "Public catering",
    "cat.beauty.desc": "Beauty salons, fitness, spa",

    // Subcategories - Automobiles
    "subcat.dealers": "Car Dealerships",
    "subcat.service": "Auto Service",
    "subcat.parts": "Auto Parts",
    "subcat.tires": "Tire Service",
    // Subcategories - Construction
    "subcat.companies": "Construction Companies",
    "subcat.materials": "Building Materials",
    "subcat.renovation": "Renovation & Finishing",
    "subcat.design": "Design",
    // Subcategories - Medicine
    "subcat.clinics": "Clinics",
    "subcat.pharmacies": "Pharmacies",
    "subcat.dental": "Dentistry",
    "subcat.diagnostics": "Diagnostics",
    // Subcategories - Education
    "subcat.universities": "Universities",
    "subcat.courses": "Courses",
    "subcat.kindergartens": "Kindergartens",
    "subcat.schools": "Schools",
    // Subcategories - Finance
    "subcat.banks": "Banks",
    "subcat.insurance": "Insurance",
    "subcat.loans": "Loans",
    "subcat.exchange": "Currency Exchange",
    // Subcategories - IT
    "subcat.it-companies": "IT Companies",
    "subcat.isp": "Internet Providers",
    "subcat.software": "Software Development",
    "subcat.repair": "Tech Repair",
    // Subcategories - Trade
    "subcat.food": "Food Products",
    "subcat.clothing": "Clothing & Footwear",
    "subcat.electronics": "Electronics",
    "subcat.furniture": "Furniture",
    // Subcategories - Services
    "subcat.legal": "Legal Services",
    "subcat.accounting": "Accounting",
    "subcat.cleaning": "Cleaning",
    "subcat.translation": "Translation",
    // Subcategories - Transport
    "subcat.cargo": "Freight",
    "subcat.taxi": "Taxi",
    "subcat.rental": "Car Rental",
    "subcat.logistics": "Logistics",
    // Subcategories - Real Estate
    "subcat.agencies": "Agencies",
    "subcat.developers": "Developers",
    "subcat.rent": "Rental",
    "subcat.commercial": "Commercial",
    // Subcategories - Restaurants
    "subcat.restaurants": "Restaurants",
    "subcat.cafes": "Cafes",
    "subcat.fastfood": "Fast Food",
    "subcat.delivery": "Food Delivery",
    // Subcategories - Beauty
    "subcat.salons": "Beauty Salons",
    "subcat.fitness": "Fitness Clubs",
    "subcat.spa": "SPA",
    "subcat.barbershops": "Barbershops",

    // News
    "news.savushkin.name": "Savushkin Product",
    "news.savushkin.title": "Savushkin Product expands dairy exports to China",
    "news.savushkin.excerpt": "Brest dairy plant increased shipments to Asian countries by 25%. The company opens a new premium cheese production line for export markets.",
    "news.santabremor.name": "Santa Bremor",
    "news.santabremor.title": "Santa Bremor opens new production complex",
    "news.santabremor.excerpt": "The largest fish producer in Belarus invests in capacity expansion. The new plant will increase production volume by 40%.",
    "news.alutech.name": "Alutech",
    "news.alutech.title": "Alutech enters Central Asian markets",
    "news.alutech.excerpt": "The manufacturer of aluminum profiles and roller systems opens offices in Kazakhstan and Uzbekistan. The company plans to double exports by 2027.",

    // Services section
    "services.title": "Business Services",
    "services.subtitle": "Comprehensive solutions for your business development and automation",
    "services.consultation": "Need consultation?",
    "services.consultationDesc": "We will find the optimal solution for your business",
    "services.contactUs": "Contact Us",

    // News
    "news.corporate": "Belarus Corporate News",
    "news.corporateSubtitle": "Current events from leading enterprises",
    "news.goToWebsite": "Go to website",

    // About section
    "about.convenientSearch": "Convenient Search",
    "about.convenientSearchDesc": "Find companies by name, category or region. Smart search with suggestions.",
    "about.aiAssistant": "AI Assistant",
    "about.aiAssistantDesc": "Submit a request through the AI assistant, and it will automatically send it to suitable companies.",
    "about.directContact": "Direct Contact",
    "about.directContactDesc": "Contact companies directly via phone, email, messengers.",
    "about.aiExplanation": "If you need to purchase a product or service, you can submit a request through our AI assistant. The assistant will automatically send your request to companies and organizations that offer this product or service.",
    "about.aiPlatform": "BiznesInfo is not just a directory, but an AI platform connecting customers and businesses.",
    "about.submitRequest": "submit request",

    // Services categories
    "services.marketing": "Marketing & Strategy",
    "services.automation": "Business Automation",
    "services.digital": "Digital Services",
    "services.aiIntegrations": "AI & Integrations",
    "services.analysis": "Analysis & Strategy",
    "services.analysisDesc": "Detailed marketing analysis and data-driven growth strategy",
    "services.leads": "Lead Generation",
    "services.leadsDesc": "Lead generation through optimized advertising channels",
    "services.processAutomation": "Process Automation",
    "services.processAutomationDesc": "Reducing team workload and increasing conversion",
    "services.crm": "CRM Systems",
    "services.crmDesc": "Implementation and configuration of customer management systems",
    "services.websites": "Website Development",
    "services.websitesDesc": "Corporate websites, landing pages and online stores",
    "services.seo": "SEO Promotion",
    "services.seoDesc": "Optimization for Yandex and Google search engines",
    "services.contextAds": "Contextual Advertising",
    "services.contextAdsDesc": "Advertising on Google, Yandex, Meta and social networks",
    "services.aiBots": "AI Bots & Chatbots",
    "services.aiBotsDesc": "Smart bots for Telegram, WhatsApp and websites",
    "services.integrations": "System Integrations",
    "services.integrationsDesc": "Connection between CRM, 1C, websites and external services",

    // Search suggestions
    "search.category": "Category",
    "search.section": "Section",
    "search.company": "Company",
    "search.subcategories": "subcategories",

    // Work hours days
    "days.weekdays": "Mon-Fri",
    "days.saturday": "Sat",
    "days.sunday": "Sun",
    "days.dayOff": "Day off",
    "days.roundClock": "24/7",
    "days.byAppointment": "By appointment",

    // Company page UI
    "company.quickActions": "Quick Actions",
    "company.locationOnMap": "Location on Map",
    "company.buildRoute": "Build Route",
    "company.found": "Found",

    // Filter labels
    "filter.region": "Region",

    // Company data - Company 1 (24pds)
    "company.1.name": "24pds ProDieselService",
    "company.1.address": "Minsk, Betonny proezd, 19A",
    "company.1.description": "Auto electrics repair, fuel injection pumps, suspension and tire service",
    "company.1.about": "ProDieselService is a professional auto service with many years of experience. We specialize in diesel engine repair, fuel equipment and auto electrics. Our specialists use modern diagnostic equipment.",
    "company.1.services": "Fuel pump repair, Injector repair, Engine diagnostics, Auto electrics repair, Tire service, Suspension repair",
    "company.1.products": "Diesel engine parts, Fuel injectors, Filters",

    // Company 33 (МедЦентр Плюс)
    "company.33.name": "MedCenter Plus",
    "company.33.address": "Minsk, Surganova st., 47B",
    "company.33.description": "Multidisciplinary medical center",
    "company.33.about": "MedCenter Plus is a modern multidisciplinary clinic in the center of Minsk. Appointments are conducted by doctors of the highest category. Own laboratory and diagnostic equipment.",
    "company.33.services": "Therapy, Cardiology, Neurology, Gynecology, Urology, Ultrasound, Laboratory tests",

    // Company 45 (IT Solutions)
    "company.45.name": "IT Solutions",
    "company.45.address": "Minsk, Kuprevicha st., 1/1",
    "company.45.description": "Software development",
    "company.45.about": "IT Solutions is a software development company. We create web applications, mobile applications, enterprise systems.",
    "company.45.services": "Web development, Mobile applications, ERP systems, CRM, Technical support",

    // Companies 2-20 (Auto)
    "company.2.name": "Truckinterservice LLC",
    "company.2.address": "Minsk district, Privolny, Mira st., 14/40",
    "company.2.description": "Repair of trucks and cars, tractors and trailers",
    "company.3.name": "Auto Center PRO-WE",
    "company.3.address": "Brest district, Cherni village, Zelenaya st., 49",
    "company.3.description": "3D wheel alignment for cars and trucks",
    "company.4.name": "Airservice",
    "company.4.address": "Minsk district, Privolny, Mira st., 12",
    "company.4.description": "Service station for trucks and special vehicles",
    "company.5.name": "Vestavto JSC",
    "company.5.address": "Brest, Kommercheskaya st., 17",
    "company.5.description": "Truck repair, tire service",
    "company.6.name": "AutoMaster Plus",
    "company.6.address": "Minsk, Pritytskogo st., 62",
    "company.6.description": "Full range of car repair services",
    "company.7.name": "STO Profi Gomel",
    "company.7.address": "Gomel, Sovetskaya st., 78",
    "company.7.description": "Diagnostics, engine repair, chassis repair",
    "company.8.name": "AutoService Europe",
    "company.8.address": "Vitebsk, Moskovsky ave., 25",
    "company.8.description": "Specialized service for European cars",
    "company.9.name": "YaMZ Regional Center",
    "company.9.address": "Minsk, Babushkina st., 21",
    "company.9.description": "YaMZ engine repair, diagnostics",
    "company.10.name": "Grodno-Auto Service",
    "company.10.address": "Grodno, Gorkogo st., 91",
    "company.10.description": "Complete car repair for all brands",
    "company.11.name": "Mogilev AutoTechCenter",
    "company.11.address": "Mogilev, Chelyuskintsev st., 45",
    "company.11.description": "Body repair, painting, polishing",
    "company.12.name": "BelDieselService",
    "company.12.address": "Minsk, Radialnaya st., 15",
    "company.12.description": "Diesel engine and fuel system repair",
    "company.13.name": "AutoDetal",
    "company.13.address": "Minsk, Dolgobrodskaya st., 24",
    "company.13.description": "Spare parts for all car brands",
    "company.14.name": "Truck Parts BEL",
    "company.14.address": "Minsk, Kazintsa st., 86",
    "company.14.description": "Parts for MAZ, KAMAZ trucks",
    "company.15.name": "Automir Brest",
    "company.15.address": "Brest, Moskovskaya st., 332",
    "company.15.description": "Auto parts wholesale and retail",
    "company.16.name": "Parts Plus Gomel",
    "company.16.address": "Gomel, Barykina st., 150",
    "company.16.description": "Original and aftermarket parts",
    "company.17.name": "VitAvtoZap",
    "company.17.address": "Vitebsk, Stroiteley ave., 18",
    "company.17.description": "Parts for foreign cars, regional delivery",
    "company.18.name": "TireService 24",
    "company.18.address": "Minsk, Timiryazeva st., 67",
    "company.18.description": "24/7 tire service, tire storage",
    "company.19.name": "Koleso Brest",
    "company.19.address": "Brest, Gogolya st., 78",
    "company.19.description": "Tire service, balancing, rim repair",
    "company.20.name": "ShinaGomel",
    "company.20.address": "Gomel, Sovetskaya st., 136",
    "company.20.description": "Sale and installation of all tire sizes",

    // Companies 21-32 (Construction)
    "company.21.name": "StroyMinsk LLC",
    "company.21.address": "Minsk, Kalvariyskaya st., 25",
    "company.21.description": "Turnkey residential and commercial construction",
    "company.22.name": "BrestStroy",
    "company.22.address": "Brest, Lenina st., 45",
    "company.22.description": "Construction work of any complexity",
    "company.23.name": "GomelZhilStroy",
    "company.23.address": "Gomel, Lenina ave., 55",
    "company.23.description": "Multi-apartment building construction",
    "company.24.name": "Vitebskstroy",
    "company.24.address": "Vitebsk, Zamkovaya st., 20",
    "company.24.description": "General construction contractor",
    "company.25.name": "GrodnoPromStroy",
    "company.25.address": "Grodno, Sovetskaya st., 18",
    "company.25.description": "Industrial and civil construction",
    "company.26.name": "MogilevStroyInvest",
    "company.26.address": "Mogilev, Pervomayskaya st., 75",
    "company.26.description": "Investment construction",
    "company.27.name": "Building Materials BEL",
    "company.27.address": "Minsk, Kazintsa st., 120",
    "company.27.description": "Wholesale building materials",
    "company.28.name": "Keramin-Brest",
    "company.28.address": "Brest, Moskovskaya st., 275",
    "company.28.description": "Ceramic tiles, plumbing",
    "company.29.name": "Construction Base Gomel",
    "company.29.address": "Gomel, Barykina st., 200",
    "company.29.description": "Everything for construction and renovation",
    "company.30.name": "RemontPlus",
    "company.30.address": "Minsk, Surganova st., 57A",
    "company.30.description": "Turnkey apartment renovation",
    "company.31.name": "GomelRemont",
    "company.31.address": "Gomel, Lenina ave., 100",
    "company.31.description": "Apartment and office renovation",
    "company.32.name": "EuroRemont Vitebsk",
    "company.32.address": "Vitebsk, Lenina st., 45",
    "company.32.description": "Quality renovation of any complexity",

    // Companies 34-44 (Medicine)
    "company.34.name": "Lode Clinic",
    "company.34.address": "Minsk, Pritytskogo st., 140",
    "company.34.description": "Private medical clinic",
    "company.35.name": "Medical Center Brest",
    "company.35.address": "Brest, Sovetskaya st., 67",
    "company.35.description": "Diagnostics and treatment",
    "company.36.name": "GomelMed",
    "company.36.address": "Gomel, Sovetskaya st., 45",
    "company.36.description": "Modern medical center",
    "company.37.name": "Vitebsk Medical Center",
    "company.37.address": "Vitebsk, Frunze ave., 80",
    "company.37.description": "Wide range of medical services",
    "company.38.name": "Dentistry 32",
    "company.38.address": "Minsk, Nemiga st., 38",
    "company.38.description": "Modern dental clinic",
    "company.39.name": "DentaVita",
    "company.39.address": "Minsk, Skryganova st., 14",
    "company.39.description": "Implantation, prosthetics, treatment",
    "company.40.name": "Ulybka Dentistry",
    "company.40.address": "Vitebsk, Zamkovaya st., 12",
    "company.40.description": "Dental services for the whole family",
    "company.41.name": "Dental-Brest",
    "company.41.address": "Brest, Gogolya st., 55",
    "company.41.description": "Treatment, prosthetics, orthodontics",
    "company.42.name": "First Aid Pharmacy",
    "company.42.address": "Minsk, Nezavisimosti ave., 58",
    "company.42.description": "Wide range of medications",
    "company.43.name": "Health Pharmacy",
    "company.43.address": "Grodno, Sovetskaya st., 5",
    "company.43.description": "Medicines and medical supplies",
    "company.44.name": "Farmacia Gomel",
    "company.44.address": "Gomel, Sovetskaya st., 97",
    "company.44.description": "Pharmacy with home delivery",

    // Companies 46-55 (IT, Trade)
    "company.46.name": "WebDev Grodno",
    "company.46.address": "Grodno, Gorkogo st., 87",
    "company.46.description": "Website and web application development",
    "company.47.name": "SoftMinsk",
    "company.47.address": "Minsk, Timiryazeva st., 72",
    "company.47.description": "Mobile app development",
    "company.48.name": "IT-Service Brest",
    "company.48.address": "Brest, Sovetskaya st., 100",
    "company.48.description": "Computer and laptop repair",
    "company.49.name": "CompMaster",
    "company.49.address": "Minsk, Nemiga st., 12",
    "company.49.description": "Urgent tech repair",
    "company.50.name": "ElectroWorld",
    "company.50.address": "Minsk, Nezavisimosti ave., 150",
    "company.50.description": "Home appliances and electronics",
    "company.51.name": "TechnoPlus",
    "company.51.address": "Gomel, Sovetskaya st., 1",
    "company.51.description": "Computers, phones, accessories",
    "company.52.name": "Furniture House",
    "company.52.address": "Mogilev, Pervomayskaya st., 25",
    "company.52.description": "Home and office furniture",
    "company.53.name": "FurnitureGrad",
    "company.53.address": "Minsk, Uruchskaya st., 19",
    "company.53.description": "Belarusian furniture manufacturers",
    "company.54.name": "Fashion and Style",
    "company.54.address": "Minsk, Nemiga st., 3",
    "company.54.description": "Brand clothing and footwear",
    "company.55.name": "Clothing Brest",
    "company.55.address": "Brest, Sovetskaya st., 65",
    "company.55.description": "Clothing for the whole family",

    // Companies 56-77 (Restaurants, Beauty, Services, Transport, Real Estate)
    "company.56.name": "Restaurant Minsk",
    "company.56.address": "Minsk, Pobediteley ave., 17",
    "company.56.description": "Belarusian and European cuisine",
    "company.57.name": "Kamyanitsa",
    "company.57.address": "Minsk, Svobody sq., 3",
    "company.57.description": "Traditional Belarusian cuisine",
    "company.58.name": "Restaurant Brest",
    "company.58.address": "Brest, Sovetskaya st., 49",
    "company.58.description": "European cuisine, banquets",
    "company.59.name": "Cafe Uyut",
    "company.59.address": "Brest, Sovetskaya st., 50",
    "company.59.description": "Cozy cafe with home-style cooking",
    "company.60.name": "Coffee Shop Gomel",
    "company.60.address": "Gomel, Lenina ave., 18",
    "company.60.description": "Coffee, desserts, breakfast",
    "company.61.name": "Pizzeria Italia",
    "company.61.address": "Minsk, Surganova st., 27",
    "company.61.description": "Italian pizza, delivery",
    "company.62.name": "Aesthetica Beauty Salon",
    "company.62.address": "Minsk, Nemiga st., 40",
    "company.62.description": "Full range of beauty services",
    "company.63.name": "Bravo Beauty Studio",
    "company.63.address": "Minsk, Pritytskogo st., 83",
    "company.63.description": "Manicure, pedicure, hairdressing",
    "company.64.name": "Victoria Salon",
    "company.64.address": "Brest, Sovetskaya st., 78",
    "company.64.description": "Haircuts, coloring, care",
    "company.65.name": "Energy Fitness Club",
    "company.65.address": "Minsk, Pritytskogo st., 156",
    "company.65.description": "Gym, group classes",
    "company.66.name": "Relax SPA Center",
    "company.66.address": "Minsk, Surganova st., 5A",
    "company.66.description": "Massage, sauna, cosmetology",
    "company.67.name": "TOPGUN Barbershop",
    "company.67.address": "Minsk, Zybitskaya st., 6",
    "company.67.description": "Men's haircuts and beard care",
    "company.68.name": "Law Firm Pravo",
    "company.68.address": "Minsk, Nezavisimosti ave., 72",
    "company.68.description": "Legal consultations and representation",
    "company.69.name": "Law Office Brest",
    "company.69.address": "Brest, Lenina st., 31",
    "company.69.description": "Legal services",
    "company.70.name": "BuhUchyot Service",
    "company.70.address": "Minsk, Tolbukhina st., 2",
    "company.70.description": "Accounting services for business",
    "company.71.name": "Cleaning Profi",
    "company.71.address": "Minsk, Kazintsa st., 52",
    "company.71.description": "Apartment, office, cottage cleaning",
    "company.72.name": "BelGruzPerevozki",
    "company.72.address": "Minsk, Radialnaya st., 40A",
    "company.72.description": "Freight transport in Belarus and CIS",
    "company.73.name": "Taxi Minsk 135",
    "company.73.address": "Minsk",
    "company.73.description": "Taxi in Minsk and region",
    "company.74.name": "AutoProkat",
    "company.74.address": "Minsk, Pritytskogo st., 60",
    "company.74.description": "Car rental without driver",
    "company.75.name": "Your Home Agency",
    "company.75.address": "Minsk, Nezavisimosti ave., 95",
    "company.75.description": "Purchase, sale, rental of real estate",
    "company.76.name": "A-100 Development",
    "company.76.address": "Minsk, Kirova st., 8",
    "company.76.description": "Residential complex construction",
    "company.77.name": "Office Rental BC",
    "company.77.address": "Minsk, Surganova st., 61",
    "company.77.description": "Commercial real estate",
  },

  be: {
    // Header
    "nav.catalog": "Каталог",
    "nav.news": "Навіны",
    "nav.promotions": "Акцыі",
    "nav.about": "Пра праект",
    "nav.addCompany": "Дадаць арганізацыю",
    "nav.favorites": "Абранае",

    // Search
    "search.placeholder": "Назва кампаніі або паслуга",
    "search.region": "Выбраць рэгіён",
    "search.allRegions": "Усе рэгіёны",
    "search.find": "Знайсці",
    "search.results": "Вынікі пошуку",
    "search.found": "Знойдзена",

    // Main page
    "hero.title": "Бізнес-даведнік Беларусі",
    "hero.subtitle": "Пошук прадпрыемстваў, арганізацый і кампаній. Тавары і паслугі ад надзейных партнёраў.",
    "stats.companies": "Кампаній",
    "stats.categories": "Катэгорый",
    "stats.regions": "Рэгіёнаў",

    // Catalog
    "catalog.title": "Каталог па катэгорыях",
    "catalog.subcategories": "Падкатэгорыі",
    "catalog.companies": "Кампаніі",
    "catalog.backToCatalog": "Вярнуцца ў каталог",
    "catalog.backToCategory": "Вярнуцца да катэгорыі",

    // Company
    "company.about": "Пра кампанію",
    "company.products": "Прадукцыя",
    "company.services": "Паслугі",
    "company.vacancies": "Вакансіі",
    "company.gallery": "Фотагалерэя",
    "company.workHours": "Час працы",
    "company.contacts": "Кантакты",
    "company.phone": "Тэлефон",
    "company.email": "Email",
    "company.website": "Сайт",
    "company.address": "Адрас",
    "company.call": "Патэлефанаваць",
    "company.write": "Напісаць",
    "company.details": "Падрабязней",
    "company.reviews": "водгукаў",
    "company.notFound": "Кампаніі не знойдзены",
    "company.notFoundDesc": "У выбраным рэгіёне няма кампаній у гэтай катэгорыі",
    "company.showAllRegions": "Паказаць усе рэгіёны",

    // AI Assistant
    "ai.title": "AI Assistent",
    "ai.description": "Пакіньце заяўку праз AI-асістэнта. Ён аўтаматычна разашле ваш запыт кампаніям.",
    "ai.inactive": "AI-асістэнт недаступны",
    "ai.personalAssistant": "Ваш персанальны памочнік",
    "ai.requestSent": "Заяўка адпраўлена!",
    "ai.requestProcessing": "AI-асістэнт апрацуе ваш запыт і разашле яго падыходзячым кампаніям.",
    "ai.placeholder": "Апішыце, што вам трэба знайсці або замовіць...",
    "ai.sendRequest": "Адправіць запыт",
    "ai.requestTo": "Запыт у",
    "ai.prioritySent": "Заяўка адпраўлена з прыярытэтам!",
    "ai.priorityDesc": "Кампанія атрымае ваш запыт у першую чаргу.",
    "ai.describePlaceholder": "Апішыце ваш запыт...",

    // Regions
    "region.minsk": "Мінск",
    "region.minsk-region": "Мінская вобласць",
    "region.brest": "Брэсцкая вобласць",
    "region.vitebsk": "Віцебская вобласць",
    "region.gomel": "Гомельская вобласць",
    "region.grodno": "Гродзенская вобласць",
    "region.mogilev": "Магілёўская вобласць",

    // Messages
    "message.title": "Напісаць паведамленне",
    "message.selectChannel": "Выберыце спосаб сувязі",
    "message.yourMessage": "Ваша паведамленне",
    "message.send": "Адправіць",

    // News
    "news.title": "Навіны",
    "news.readMore": "Чытаць далей",

    // Footer
    "footer.forBusiness": "Для бізнесу",
    "footer.addCompany": "Дадаць кампанію",
    "footer.advertising": "Рэклама на сайце",
    "footer.tariffs": "Тарыфы",
    "footer.catalog": "Каталог",
    "footer.contacts": "Кантакты",
    "footer.agreement": "Карыстальніцкае пагадненне",
    "footer.offer": "Публічны дагавор (аферта)",
    "footer.adRequest": "Заяўка на размяшчэнне рэкламы",
    "footer.rights": "Усе правы абаронены",
    "footer.information": "Інфармацыя",

    // Add company form
    "addCompany.companyInfo": "Інфармацыя пра кампанію",
    "addCompany.contactInfo": "Кантактная інфармацыя кампаніі",

    // Favorites
    "favorites.title": "Абранае",
    "favorites.empty": "У вас пакуль няма абраных кампаній",
    "favorites.add": "Дадаць у абранае",
    "favorites.remove": "Выдаліць з абранага",

    // Common
    "common.loading": "Загрузка...",
    "common.error": "Памылка",
    "common.back": "Назад",
    "common.home": "Галоўная",

    // Categories
    "cat.automobiles": "Аўтамабілі",
    "cat.construction": "Будаўніцтва",
    "cat.medicine": "Медыцына",
    "cat.education": "Адукацыя",
    "cat.finance": "Фінансы",
    "cat.it-telecom": "IT і Тэлекам",
    "cat.trade": "Гандаль",
    "cat.services": "Паслугі",
    "cat.transport": "Транспарт",
    "cat.realestate": "Нерухомасць",
    "cat.restaurants": "Рэстараны і кафэ",
    "cat.beauty": "Прыгажосць і здароўе",

    // Category descriptions
    "cat.automobiles.desc": "Аўтасалоны, аўтасэрвісы, запчасткі",
    "cat.construction.desc": "Будаўнічыя кампаніі і матэрыялы",
    "cat.medicine.desc": "Клінікі, аптэкі, медыцынскія паслугі",
    "cat.education.desc": "Навучальныя ўстановы, курсы",
    "cat.finance.desc": "Банкі, страхаванне, інвестыцыі",
    "cat.it-telecom.desc": "IT-кампаніі, сувязь, інтэрнэт",
    "cat.trade.desc": "Крамы, аптовы гандаль",
    "cat.services.desc": "Бытавыя і прафесійныя паслугі",
    "cat.transport.desc": "Грузаперавозкі, лагістыка, таксі",
    "cat.realestate.desc": "Агенцтвы, забудоўшчыкі",
    "cat.restaurants.desc": "Грамадскае харчаванне",
    "cat.beauty.desc": "Салоны прыгажосці, фітнес, спа",

    // Subcategories - Automobiles
    "subcat.dealers": "Аўтасалоны",
    "subcat.service": "Аўтасэрвіс",
    "subcat.parts": "Аўтазапчасткі",
    "subcat.tires": "Шынамантаж",
    // Subcategories - Construction
    "subcat.companies": "Будаўнічыя кампаніі",
    "subcat.materials": "Будматэрыялы",
    "subcat.renovation": "Рамонт і аздабленне",
    "subcat.design": "Праектаванне",
    // Subcategories - Medicine
    "subcat.clinics": "Клінікі",
    "subcat.pharmacies": "Аптэкі",
    "subcat.dental": "Стаматалогія",
    "subcat.diagnostics": "Дыягностыка",
    // Subcategories - Education
    "subcat.universities": "Універсітэты",
    "subcat.courses": "Курсы",
    "subcat.kindergartens": "Дзіцячыя сады",
    "subcat.schools": "Школы",
    // Subcategories - Finance
    "subcat.banks": "Банкі",
    "subcat.insurance": "Страхаванне",
    "subcat.loans": "Крэдытаванне",
    "subcat.exchange": "Абмен валют",
    // Subcategories - IT
    "subcat.it-companies": "IT-кампаніі",
    "subcat.isp": "Інтэрнэт-правайдэры",
    "subcat.software": "Распрацоўка ПЗ",
    "subcat.repair": "Рамонт тэхнікі",
    // Subcategories - Trade
    "subcat.food": "Харчовыя прадукты",
    "subcat.clothing": "Адзенне і абутак",
    "subcat.electronics": "Электроніка",
    "subcat.furniture": "Мэбля",
    // Subcategories - Services
    "subcat.legal": "Юрыдычныя паслугі",
    "subcat.accounting": "Бухгалтэрыя",
    "subcat.cleaning": "Клінінг",
    "subcat.translation": "Пераклады",
    // Subcategories - Transport
    "subcat.cargo": "Грузаперавозкі",
    "subcat.taxi": "Таксі",
    "subcat.rental": "Арэнда аўто",
    "subcat.logistics": "Лагістыка",
    // Subcategories - Real Estate
    "subcat.agencies": "Агенцтвы",
    "subcat.developers": "Забудоўшчыкі",
    "subcat.rent": "Арэнда",
    "subcat.commercial": "Камерцыйная",
    // Subcategories - Restaurants
    "subcat.restaurants": "Рэстараны",
    "subcat.cafes": "Кафэ",
    "subcat.fastfood": "Фастфуд",
    "subcat.delivery": "Дастаўка ежы",
    // Subcategories - Beauty
    "subcat.salons": "Салоны прыгажосці",
    "subcat.fitness": "Фітнес-клубы",
    "subcat.spa": "СПА",
    "subcat.barbershops": "Барбершопы",

    // News
    "news.savushkin.name": "Савушкін прадукт",
    "news.savushkin.title": "Савушкін прадукт пашырае экспарт малочнай прадукцыі ў Кітай",
    "news.savushkin.excerpt": "Брэсцкі малочны камбінат павялічыў пастаўкі ў краіны Азіі на 25%. Кампанія адкрывае новую лінію па вытворчасці сыроў прэміум-класа для экспартных рынкаў.",
    "news.santabremor.name": "Санта Брэмор",
    "news.santabremor.title": "Санта Брэмор адкрывае новы вытворчы комплекс",
    "news.santabremor.excerpt": "Найбуйнейшы вытворца рыбнай прадукцыі ў Беларусі інвестуе ў пашырэнне магутнасцей. Новы завод дазволіць павялічыць аб'ём вытворчасці на 40%.",
    "news.alutech.name": "Алютэх",
    "news.alutech.title": "Алютэх выходзіць на рынкі Цэнтральнай Азіі",
    "news.alutech.excerpt": "Вытворца алюмініевых профіляў і ралетных сістэм адкрывае прадстаўніцтвы ў Казахстане і Узбекістане. Кампанія плануе падвоіць экспарт да 2027 года.",

    // Services section
    "services.title": "Паслугі для бізнесу",
    "services.subtitle": "Комплексныя рашэнні для развіцця і аўтаматызацыі вашага бізнесу",
    "services.consultation": "Патрэбна кансультацыя?",
    "services.consultationDesc": "Падбяром аптымальнае рашэнне для вашага бізнесу",
    "services.contactUs": "Напісаць нам",

    // News
    "news.corporate": "Навіны кампаній Беларусі",
    "news.corporateSubtitle": "Актуальныя падзеі вядучых прадпрыемстваў краіны",
    "news.goToWebsite": "Перайсці на сайт",

    // About section
    "about.convenientSearch": "Зручны пошук",
    "about.convenientSearchDesc": "Знаходзіце кампаніі па назве, катэгорыі або рэгіёне. Разумны пошук з падказкамі.",
    "about.aiAssistant": "AI-асістэнт",
    "about.aiAssistantDesc": "Пакіньце заяўку праз AI-асістэнта, і ён аўтаматычна разашле яе падыходзячым кампаніям.",
    "about.directContact": "Прамы кантакт",
    "about.directContactDesc": "Звязвайцеся з кампаніямі напрамую праз тэлефон, email, месэнджары.",
    "about.aiExplanation": "Калі вам неабходна набыць тавар ці паслугу, вы можаце пакінуць заяўку праз нашага AI-асістэнта. Асістэнт аўтаматычна разашле ваш запыт кампаніям і арганізацыям, якія прапануюць дадзены тавар ці паслугу.",
    "about.aiPlatform": "BiznesInfo — гэта не даведнік, а AI-платформа, якая злучае кліентаў і бізнес.",
    "about.submitRequest": "адправіць заяўку",

    // Services categories
    "services.marketing": "Маркетынг і стратэгія",
    "services.automation": "Аўтаматызацыя бізнесу",
    "services.digital": "Digital-паслугі",
    "services.aiIntegrations": "AI і інтэграцыі",
    "services.analysis": "Аналіз і стратэгія",
    "services.analysisDesc": "Дэталёвы маркетынгавы аналіз і фарміраванне стратэгіі росту на аснове дадзеных",
    "services.leads": "Прыцягненне заявак",
    "services.leadsDesc": "Лідагенерацыя праз аптымізаваныя рэкламныя каналы",
    "services.processAutomation": "Аўтаматызацыя працэсаў",
    "services.processAutomationDesc": "Зніжэнне нагрузкі на каманду і павышэнне канверсіі",
    "services.crm": "CRM-сістэмы",
    "services.crmDesc": "Укараненне і настройка сістэм кіравання кліентамі",
    "services.websites": "Стварэнне сайтаў",
    "services.websitesDesc": "Карпаратыўныя сайты, лендынгі і інтэрнэт-крамы",
    "services.seo": "SEO-прасоўванне",
    "services.seoDesc": "Аптымізацыя для пошукавых сістэм Яндэкс і Google",
    "services.contextAds": "Кантэкстная рэклама",
    "services.contextAdsDesc": "Рэклама ў Google, Яндэкс, Meta і сацыяльных сетках",
    "services.aiBots": "AI-боты і чат-боты",
    "services.aiBotsDesc": "Разумныя боты для Telegram, WhatsApp і вэб-сайтаў",
    "services.integrations": "Інтэграцыі сістэм",
    "services.integrationsDesc": "Сувязь паміж CRM, 1С, сайтамі і знешнімі сэрвісамі",

    // Search suggestions
    "search.category": "Катэгорыя",
    "search.section": "Раздзел",
    "search.company": "Кампанія",
    "search.subcategories": "падкатэгорый",

    // Work hours days
    "days.weekdays": "Пн-Пт",
    "days.saturday": "Сб",
    "days.sunday": "Нд",
    "days.dayOff": "Выхадны",
    "days.roundClock": "Цалыя суткі",
    "days.byAppointment": "Па запісе",

    // Company page UI
    "company.quickActions": "Хуткія дзеянні",
    "company.locationOnMap": "Размяшчэнне на карце",
    "company.buildRoute": "Пабудаваць маршрут",
    "company.found": "Знойдзена",

    // Filter labels
    "filter.region": "Рэгіён",

    // Company data - Company 1 (24pds)
    "company.1.name": "24pds СТА ПраДызельСэрвіс",
    "company.1.address": "Мінск, Бятонны праезд, 19А",
    "company.1.description": "Рамонт аўтаэлектрыкі, ТНВД, падвескі і шынамантаж",
    "company.1.about": "СТА ПраДызельСэрвіс — гэта прафесійны аўтасэрвіс з шматгадовым вопытам працы. Мы спецыялізуемся на рамонце дызельных рухавікоў, паліўнай апаратуры і аўтаэлектрыкі.",
    "company.1.services": "Рамонт ТНВД, Рамонт форсунак, Дыягностыка рухавіка, Рамонт аўтаэлектрыкі, Шынамантаж, Рамонт падвескі",
    "company.1.products": "Запчасткі для дызельных рухавікоў, Паліўныя форсункі, Фільтры",

    // Company 33 (МедЦентр Плюс)
    "company.33.name": "МедЦэнтр Плюс",
    "company.33.address": "Мінск, вул. Сурганава, 47Б",
    "company.33.description": "Шматпрофільны медыцынскі цэнтр",
    "company.33.about": "МедЦэнтр Плюс — сучасная шматпрофільная клініка ў цэнтры Мінска. Прыём вядуць лекары вышэйшай катэгорыі.",
    "company.33.services": "Тэрапія, Кардыялогія, Неўралогія, Гінекалогія, Уралогія, УГД, Лабараторныя аналізы",

    // Company 45 (IT Solutions)
    "company.45.name": "IT Solutions",
    "company.45.address": "Мінск, вул. Купрэвіча, 1/1",
    "company.45.description": "Распрацоўка праграмнага забеспячэння",
    "company.45.about": "IT Solutions — кампанія па распрацоўцы праграмнага забеспячэння. Ствараем вэб-прыкладанні, мабільныя прыкладанні, карпаратыўныя сістэмы.",
    "company.45.services": "Вэб-распрацоўка, Мабільныя прыкладанні, ERP-сістэмы, CRM, Тэхпадтрымка",

    // Companies 2-20 (Auto)
    "company.2.name": "Тракінтэрсэрвіс ТАА",
    "company.2.address": "Мінскі р-н, пас. Прывольны, вул. Міра, 14/40",
    "company.2.description": "Рамонт грузавых і легкавых аўтамабіляў, цягачоў і прычэпаў",
    "company.3.name": "Аўтацэнтр PRO-WE",
    "company.3.address": "Брэсцкі р-н, в. Чэрні, вул. Зялёная, 49",
    "company.3.description": "3D развал-схаджэнне легкавых і грузавых аўтамабіляў",
    "company.4.name": "Аірсэрвіс ПУП",
    "company.4.address": "Мінскі р-н, пас. Прывольны, вул. Міра, 12",
    "company.4.description": "СТА па рамонце грузавой і спецыяльнай тэхнікі",
    "company.5.name": "Вестаўто СП ААТ",
    "company.5.address": "Брэст, вул. Камерцыйная, 17",
    "company.5.description": "Рамонт грузавых аўтамабіляў, шынамантаж",
    "company.6.name": "АўтаМайстар Плюс",
    "company.6.address": "Мінск, вул. Прытыцкага, 62",
    "company.6.description": "Поўны спектр паслуг па рамонце легкавых аўтамабіляў",
    "company.7.name": "СТА Профі Гомель",
    "company.7.address": "Гомель, вул. Савецкая, 78",
    "company.7.description": "Дыягностыка, рамонт рухавікоў, хадавой часткі",
    "company.8.name": "Аўтасэрвіс Еўропа",
    "company.8.address": "Віцебск, пр. Маскоўскі, 25",
    "company.8.description": "Спецыялізаваны сэрвіс для еўрапейскіх аўтамабіляў",
    "company.9.name": "Рэгіянальны цэнтр ЯМЗ",
    "company.9.address": "Мінск, вул. Бабушкіна, 21",
    "company.9.description": "Рамонт рухавікоў ЯМЗ, дыягностыка",
    "company.10.name": "Гродна-Аўто Сэрвіс",
    "company.10.address": "Гродна, вул. Горкага, 91",
    "company.10.description": "Комплексны рамонт аўтамабіляў усіх марак",
    "company.11.name": "Магілёў АўтаТэхЦэнтр",
    "company.11.address": "Магілёў, вул. Чэлюскінцаў, 45",
    "company.11.description": "Кузаўны рамонт, афарбоўка, паліроўка",
    "company.12.name": "БелДызельСэрвіс",
    "company.12.address": "Мінск, вул. Радыяльная, 15",
    "company.12.description": "Рамонт дызельных рухавікоў і паліўнай апаратуры",
    "company.13.name": "АўтаДэталь",
    "company.13.address": "Мінск, вул. Даўгабродская, 24",
    "company.13.description": "Запчасткі для легкавых аўтамабіляў усіх марак",
    "company.14.name": "Грузавыя Запчасткі БЕЛ",
    "company.14.address": "Мінск, вул. Казінца, 86",
    "company.14.description": "Запчасткі для грузавых аўтамабіляў МАЗ, КАМАЗ",
    "company.15.name": "Аўтамір Брэст",
    "company.15.address": "Брэст, вул. Маскоўская, 332",
    "company.15.description": "Аўтазапчасткі оптам і ў розніцу",
    "company.16.name": "Запчасткі Плюс Гомель",
    "company.16.address": "Гомель, вул. Барыкіна, 150",
    "company.16.description": "Арыгінальныя і неарыгінальныя запчасткі",
    "company.17.name": "ВітАўтаЗап",
    "company.17.address": "Віцебск, пр. Будаўнікоў, 18",
    "company.17.description": "Запчасткі для іншамарак, дастаўка па вобласці",
    "company.18.name": "ШынСэрвіс 24",
    "company.18.address": "Мінск, вул. Цімірязева, 67",
    "company.18.description": "Кругласутачны шынамантаж, захоўванне шын",
    "company.19.name": "Кола Брэст",
    "company.19.address": "Брэст, вул. Гогаля, 78",
    "company.19.description": "Шынамантаж, балансіроўка, рамонт дыскаў",
    "company.20.name": "ШынаГомель",
    "company.20.address": "Гомель, вул. Савецкая, 136",
    "company.20.description": "Продаж і мантаж шын усіх памераў",

    // Companies 21-32 (Construction)
    "company.21.name": "БудМінск ТАА",
    "company.21.address": "Мінск, вул. Кальварыйская, 25",
    "company.21.description": "Будаўніцтва жылых і камерцыйных аб'ектаў пад ключ",
    "company.22.name": "БрэстБуд",
    "company.22.address": "Брэст, вул. Леніна, 45",
    "company.22.description": "Будаўнічыя работы любой складанасці",
    "company.23.name": "ГомельЖылБуд",
    "company.23.address": "Гомель, пр. Леніна, 55",
    "company.23.description": "Будаўніцтва шматкватэрных дамоў",
    "company.24.name": "Віцебскбуд",
    "company.24.address": "Віцебск, вул. Замкавая, 20",
    "company.24.description": "Генеральны падрадчык будаўніцтва",
    "company.25.name": "ГроднаПрамБуд",
    "company.25.address": "Гродна, вул. Савецкая, 18",
    "company.25.description": "Прамысловае і грамадзянскае будаўніцтва",
    "company.26.name": "МагілёўБудІнвест",
    "company.26.address": "Магілёў, вул. Першамайская, 75",
    "company.26.description": "Інвестыцыйнае будаўніцтва",
    "company.27.name": "БудМатэрыялы БЕЛ",
    "company.27.address": "Мінск, вул. Казінца, 120",
    "company.27.description": "Аптовы продаж будматэрыялаў",
    "company.28.name": "Керамін-Брэст",
    "company.28.address": "Брэст, вул. Маскоўская, 275",
    "company.28.description": "Керамічная плітка, сантэхніка",
    "company.29.name": "Будбаза Гомель",
    "company.29.address": "Гомель, вул. Барыкіна, 200",
    "company.29.description": "Усё для будаўніцтва і рамонту",
    "company.30.name": "РамонтПлюс",
    "company.30.address": "Мінск, вул. Сурганава, 57А",
    "company.30.description": "Рамонт кватэр пад ключ",
    "company.31.name": "ГомельРамонт",
    "company.31.address": "Гомель, пр. Леніна, 100",
    "company.31.description": "Рамонт кватэр і офісаў",
    "company.32.name": "ЕўраРамонт Віцебск",
    "company.32.address": "Віцебск, вул. Леніна, 45",
    "company.32.description": "Якасны рамонт любой складанасці",

    // Companies 34-44 (Medicine)
    "company.34.name": "Клініка Лодэ",
    "company.34.address": "Мінск, вул. Прытыцкага, 140",
    "company.34.description": "Прыватная медыцынская клініка",
    "company.35.name": "Медыцынскі цэнтр Брэст",
    "company.35.address": "Брэст, вул. Савецкая, 67",
    "company.35.description": "Дыягностыка і лячэнне",
    "company.36.name": "ГомельМед",
    "company.36.address": "Гомель, вул. Савецкая, 45",
    "company.36.description": "Сучасны медыцынскі цэнтр",
    "company.37.name": "Віцебскі медцэнтр",
    "company.37.address": "Віцебск, пр. Фрунзэ, 80",
    "company.37.description": "Шырокі спектр медыцынскіх паслуг",
    "company.38.name": "Стаматалогія 32",
    "company.38.address": "Мінск, вул. Нямiга, 38",
    "company.38.description": "Сучасная стаматалагічная клініка",
    "company.39.name": "ДэнтаВіта",
    "company.39.address": "Мінск, вул. Скрыганава, 14",
    "company.39.description": "Імплантацыя, пратэзаванне, лячэнне",
    "company.40.name": "Стаматалогія Усмешка",
    "company.40.address": "Віцебск, вул. Замкавая, 12",
    "company.40.description": "Стаматалагічныя паслугі для ўсёй сям'і",
    "company.41.name": "Дэнтал-Брэст",
    "company.41.address": "Брэст, вул. Гогаля, 55",
    "company.41.description": "Лячэнне, пратэзаванне, артадонтыя",
    "company.42.name": "Аптэка Першая Дапамога",
    "company.42.address": "Мінск, пр. Незалежнасці, 58",
    "company.42.description": "Шырокі асартымент лекаў",
    "company.43.name": "Аптэка Здароўе",
    "company.43.address": "Гродна, вул. Савецкая, 5",
    "company.43.description": "Лекі і медыцынскія тавары",
    "company.44.name": "Фармацыя Гомель",
    "company.44.address": "Гомель, вул. Савецкая, 97",
    "company.44.description": "Аптэка з дастаўкай на дом",

    // Companies 46-55 (IT, Trade)
    "company.46.name": "WebDev Гродна",
    "company.46.address": "Гродна, вул. Горкага, 87",
    "company.46.description": "Стварэнне сайтаў і вэб-прыкладанняў",
    "company.47.name": "SoftMinsk",
    "company.47.address": "Мінск, вул. Цімірязева, 72",
    "company.47.description": "Распрацоўка мабільных прыкладанняў",
    "company.48.name": "IT-Сэрвіс Брэст",
    "company.48.address": "Брэст, вул. Савецкая, 100",
    "company.48.description": "Рамонт камп'ютараў і ноўтбукаў",
    "company.49.name": "КомпМайстар",
    "company.49.address": "Мінск, вул. Нямiга, 12",
    "company.49.description": "Тэрміновы рамонт тэхнікі",
    "company.50.name": "ЭлектраСвет",
    "company.50.address": "Мінск, пр. Незалежнасці, 150",
    "company.50.description": "Бытавая тэхніка і электроніка",
    "company.51.name": "ТэхнаПлюс",
    "company.51.address": "Гомель, вул. Савецкая, 1",
    "company.51.description": "Камп'ютары, тэлефоны, аксесуары",
    "company.52.name": "Мэблевы Дом",
    "company.52.address": "Магілёў, вул. Першамайская, 25",
    "company.52.description": "Мэбля для дома і офіса",
    "company.53.name": "МэбляГрад",
    "company.53.address": "Мінск, вул. Уручская, 19",
    "company.53.description": "Мэбля беларускіх вытворцаў",
    "company.54.name": "Мода і Стыль",
    "company.54.address": "Мінск, вул. Нямiга, 3",
    "company.54.description": "Брэндавая адзенне і абутак",
    "company.55.name": "Адзенне Брэст",
    "company.55.address": "Брэст, вул. Савецкая, 65",
    "company.55.description": "Адзенне для ўсёй сям'і",

    // Companies 56-77 (Restaurants, Beauty, Services, Transport, Real Estate)
    "company.56.name": "Рэстаран Мінск",
    "company.56.address": "Мінск, пр. Пераможцаў, 17",
    "company.56.description": "Беларуская і еўрапейская кухня",
    "company.57.name": "Камяніца",
    "company.57.address": "Мінск, пл. Свабоды, 3",
    "company.57.description": "Традыцыйная беларуская кухня",
    "company.58.name": "Рэстаран Брэст",
    "company.58.address": "Брэст, вул. Савецкая, 49",
    "company.58.description": "Еўрапейская кухня, банкеты",
    "company.59.name": "Кафэ Утульнасць",
    "company.59.address": "Брэст, вул. Савецкая, 50",
    "company.59.description": "Утульнае кафэ з хатняй кухняй",
    "company.60.name": "Кававарня Гомель",
    "company.60.address": "Гомель, пр. Леніна, 18",
    "company.60.description": "Кава, дэсерты, сняданкі",
    "company.61.name": "Піцэрыя Італія",
    "company.61.address": "Мінск, вул. Сурганава, 27",
    "company.61.description": "Італьянская піца, дастаўка",
    "company.62.name": "Салон Прыгажосці Эстэтыка",
    "company.62.address": "Мінск, вул. Нямiга, 40",
    "company.62.description": "Поўны спектр касметычных паслуг",
    "company.63.name": "Студыя Прыгажосці Bravo",
    "company.63.address": "Мінск, вул. Прытыцкага, 83",
    "company.63.description": "Манікюр, педыкюр, цырульніцкія паслугі",
    "company.64.name": "Салон Вікторыя",
    "company.64.address": "Брэст, вул. Савецкая, 78",
    "company.64.description": "Стрыжкі, афарбоўка, догляд",
    "company.65.name": "Фітнес-клуб Энергія",
    "company.65.address": "Мінск, вул. Прытыцкага, 156",
    "company.65.description": "Трэнажорная зала, групавыя заняткі",
    "company.66.name": "СПА-цэнтр Рэлакс",
    "company.66.address": "Мінск, вул. Сурганава, 5А",
    "company.66.description": "Масаж, лазня, касметалогія",
    "company.67.name": "Барбершоп TOPGUN",
    "company.67.address": "Мінск, вул. Зыбіцкая, 6",
    "company.67.description": "Мужчынскія стрыжкі і догляд за барадой",
    "company.68.name": "Юрыдычная фірма Права",
    "company.68.address": "Мінск, пр. Незалежнасці, 72",
    "company.68.description": "Юрыдычныя кансультацыі і прадстаўніцтва",
    "company.69.name": "Адвакацкае бюро Брэст",
    "company.69.address": "Брэст, вул. Леніна, 31",
    "company.69.description": "Адвакацкія паслугі",
    "company.70.name": "БухУлік Сэрвіс",
    "company.70.address": "Мінск, вул. Талбухіна, 2",
    "company.70.description": "Бухгалтарскія паслугі для бізнесу",
    "company.71.name": "Клінінг Профі",
    "company.71.address": "Мінск, вул. Казінца, 52",
    "company.71.description": "Прыборка кватэр, офісаў, катэджаў",
    "company.72.name": "БелГрузПеравозкі",
    "company.72.address": "Мінск, вул. Радыяльная, 40А",
    "company.72.description": "Грузаперавозкі па Беларусі і СНД",
    "company.73.name": "Таксі Мінск 135",
    "company.73.address": "Мінск",
    "company.73.description": "Таксі па Мінску і вобласці",
    "company.74.name": "АўтаПракат",
    "company.74.address": "Мінск, вул. Прытыцкага, 60",
    "company.74.description": "Арэнда аўтамабіляў без кіроўцы",
    "company.75.name": "Агенцтва Твой Дом",
    "company.75.address": "Мінск, пр. Незалежнасці, 95",
    "company.75.description": "Купля, продаж, арэнда нерухомасці",
    "company.76.name": "А-100 Дэвелапмент",
    "company.76.address": "Мінск, вул. Кірава, 8",
    "company.76.description": "Будаўніцтва жылых комплексаў",
    "company.77.name": "Арэнда Офісаў БЦ",
    "company.77.address": "Мінск, вул. Сурганава, 61",
    "company.77.description": "Камерцыйная нерухомасць",
  },

  zh: {
    // Header
    "nav.catalog": "目录",
    "nav.news": "新闻",
    "nav.promotions": "促销",
    "nav.about": "关于项目",
    "nav.addCompany": "添加组织",
    "nav.favorites": "收藏夹",

    // Search
    "search.placeholder": "公司名称或服务",
    "search.region": "选择地区",
    "search.allRegions": "所有地区",
    "search.find": "搜索",
    "search.results": "搜索结果",
    "search.found": "找到",

    // Main page
    "hero.title": "白俄罗斯商业目录",
    "hero.subtitle": "搜索企业、组织和公司。来自可靠合作伙伴的商品和服务。",
    "stats.companies": "公司",
    "stats.categories": "类别",
    "stats.regions": "地区",

    // Catalog
    "catalog.title": "按类别目录",
    "catalog.subcategories": "子类别",
    "catalog.companies": "公司",
    "catalog.backToCatalog": "返回目录",
    "catalog.backToCategory": "返回类别",

    // Company
    "company.about": "关于公司",
    "company.products": "产品",
    "company.services": "服务",
    "company.vacancies": "职位",
    "company.gallery": "图库",
    "company.workHours": "工作时间",
    "company.contacts": "联系方式",
    "company.phone": "电话",
    "company.email": "电子邮件",
    "company.website": "网站",
    "company.address": "地址",
    "company.call": "拨打电话",
    "company.write": "发送消息",
    "company.details": "详情",
    "company.reviews": "条评论",
    "company.notFound": "未找到公司",
    "company.notFoundDesc": "所选地区没有此类别的公司",
    "company.showAllRegions": "显示所有地区",

    // AI Assistant
    "ai.title": "AI Assistent",
    "ai.description": "通过AI助手提交请求。它会自动将您的请求发送给相关公司。",
    "ai.inactive": "AI助手不可用",
    "ai.personalAssistant": "您的个人助手",
    "ai.requestSent": "请求已发送！",
    "ai.requestProcessing": "AI助手将处理您的请求并将其发送给合适的公司。",
    "ai.placeholder": "描述您需要查找或订购的内容...",
    "ai.sendRequest": "发送请求",
    "ai.requestTo": "请求发送至",
    "ai.prioritySent": "请求已优先发送！",
    "ai.priorityDesc": "公司将首先收到您的请求。",
    "ai.describePlaceholder": "描述您的请求...",

    // Regions
    "region.minsk": "明斯克",
    "region.minsk-region": "明斯克州",
    "region.brest": "布列斯特州",
    "region.vitebsk": "维捷布斯克州",
    "region.gomel": "戈梅利州",
    "region.grodno": "格罗德诺州",
    "region.mogilev": "莫吉廖夫州",

    // Messages
    "message.title": "发送消息",
    "message.selectChannel": "选择联系方式",
    "message.yourMessage": "您的消息",
    "message.send": "发送",

    // News
    "news.title": "新闻",
    "news.readMore": "阅读更多",

    // Footer
    "footer.forBusiness": "商业服务",
    "footer.addCompany": "添加公司",
    "footer.advertising": "网站广告",
    "footer.tariffs": "价格",
    "footer.catalog": "目录",
    "footer.contacts": "联系方式",
    "footer.agreement": "用户协议",
    "footer.offer": "公开要约",
    "footer.adRequest": "广告请求",
    "footer.rights": "版权所有",
    "footer.information": "信息",

    // Add company form
    "addCompany.companyInfo": "公司信息",
    "addCompany.contactInfo": "公司联系信息",

    // Favorites
    "favorites.title": "收藏夹",
    "favorites.empty": "您还没有收藏的公司",
    "favorites.add": "添加到收藏夹",
    "favorites.remove": "从收藏夹移除",

    // Common
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.back": "返回",
    "common.home": "首页",

    // Categories
    "cat.automobiles": "汽车",
    "cat.construction": "建筑",
    "cat.medicine": "医疗",
    "cat.education": "教育",
    "cat.finance": "金融",
    "cat.it-telecom": "IT和通信",
    "cat.trade": "贸易",
    "cat.services": "服务",
    "cat.transport": "运输",
    "cat.realestate": "房地产",
    "cat.restaurants": "餐厅和咖啡厅",
    "cat.beauty": "美容与健康",

    // Category descriptions
    "cat.automobiles.desc": "汽车经销商、汽车服务、零配件",
    "cat.construction.desc": "建筑公司和材料",
    "cat.medicine.desc": "诊所、药店、医疗服务",
    "cat.education.desc": "教育机构、课程",
    "cat.finance.desc": "银行、保险、投资",
    "cat.it-telecom.desc": "IT公司、通信、互联网",
    "cat.trade.desc": "商店、批发贸易",
    "cat.services.desc": "家庭和专业服务",
    "cat.transport.desc": "货运、物流、出租车",
    "cat.realestate.desc": "中介、开发商",
    "cat.restaurants.desc": "餐饮服务",
    "cat.beauty.desc": "美容院、健身、水疗",

    // Subcategories - Automobiles
    "subcat.dealers": "汽车经销商",
    "subcat.service": "汽车服务",
    "subcat.parts": "汽车零件",
    "subcat.tires": "轮胎服务",
    // Subcategories - Construction
    "subcat.companies": "建筑公司",
    "subcat.materials": "建筑材料",
    "subcat.renovation": "装修",
    "subcat.design": "设计",
    // Subcategories - Medicine
    "subcat.clinics": "诊所",
    "subcat.pharmacies": "药店",
    "subcat.dental": "牙科",
    "subcat.diagnostics": "诊断",
    // Subcategories - Education
    "subcat.universities": "大学",
    "subcat.courses": "课程",
    "subcat.kindergartens": "幼儿园",
    "subcat.schools": "学校",
    // Subcategories - Finance
    "subcat.banks": "银行",
    "subcat.insurance": "保险",
    "subcat.loans": "贷款",
    "subcat.exchange": "货币兑换",
    // Subcategories - IT
    "subcat.it-companies": "IT公司",
    "subcat.isp": "互联网提供商",
    "subcat.software": "软件开发",
    "subcat.repair": "技术维修",
    // Subcategories - Trade
    "subcat.food": "食品",
    "subcat.clothing": "服装鞋类",
    "subcat.electronics": "电子产品",
    "subcat.furniture": "家具",
    // Subcategories - Services
    "subcat.legal": "法律服务",
    "subcat.accounting": "会计",
    "subcat.cleaning": "清洁",
    "subcat.translation": "翻译",
    // Subcategories - Transport
    "subcat.cargo": "货运",
    "subcat.taxi": "出租车",
    "subcat.rental": "汽车租赁",
    "subcat.logistics": "物流",
    // Subcategories - Real Estate
    "subcat.agencies": "中介",
    "subcat.developers": "开发商",
    "subcat.rent": "租赁",
    "subcat.commercial": "商业地产",
    // Subcategories - Restaurants
    "subcat.restaurants": "餐厅",
    "subcat.cafes": "咖啡厅",
    "subcat.fastfood": "快餐",
    "subcat.delivery": "外卖",
    // Subcategories - Beauty
    "subcat.salons": "美容院",
    "subcat.fitness": "健身俱乐部",
    "subcat.spa": "水疗",
    "subcat.barbershops": "理发店",

    // News
    "news.savushkin.name": "萨武什金乳品",
    "news.savushkin.title": "萨武什金产品扩大对华乳制品出口",
    "news.savushkin.excerpt": "布列斯特乳品厂对亚洲国家的出货量增加了25%。公司为出口市场开设了新的优质奶酪生产线。",
    "news.santabremor.name": "圣布雷莫尔",
    "news.santabremor.title": "圣布雷莫尔开设新生产基地",
    "news.santabremor.excerpt": "白俄罗斯最大的鱼产品生产商投资扩大产能。新工厂将使产量增加40%。",
    "news.alutech.name": "阿鲁泰克",
    "news.alutech.title": "阿鲁泰克进入中亚市场",
    "news.alutech.excerpt": "铝型材和卷帘系统制造商在哈萨克斯坦和乌兹别克斯坦开设办事处。公司计划到2027年将出口翻一番。",

    // Services section
    "services.title": "商业服务",
    "services.subtitle": "全面的业务发展和自动化解决方案",
    "services.consultation": "需要咨询?",
    "services.consultationDesc": "我们将为您的业务找到最佳解决方案",
    "services.contactUs": "联系我们",

    // News
    "news.corporate": "白俄罗斯企业新闻",
    "news.corporateSubtitle": "领先企业的最新动态",
    "news.goToWebsite": "访问网站",

    // About section
    "about.convenientSearch": "便捷搜索",
    "about.convenientSearchDesc": "按名称、类别或地区查找公司。带建议的智能搜索。",
    "about.aiAssistant": "AI助手",
    "about.aiAssistantDesc": "通过AI助手提交请求，它会自动将请求发送给合适的公司。",
    "about.directContact": "直接联系",
    "about.directContactDesc": "通过电话、电子邮件、即时通讯直接联系公司。",
    "about.aiExplanation": "如果您需要购买产品或服务，可以通过我们的AI助手提交请求。助手会自动将您的请求发送给提供该产品或服务的公司和组织。",
    "about.aiPlatform": "BiznesInfo不仅是一个目录，而是一个连接客户和企业的AI平台。",
    "about.submitRequest": "提交请求",

    // Services categories
    "services.marketing": "营销与战略",
    "services.automation": "业务自动化",
    "services.digital": "数字服务",
    "services.aiIntegrations": "AI与集成",
    "services.analysis": "分析与战略",
    "services.analysisDesc": "详细的营销分析和基于数据的增长策略",
    "services.leads": "潜在客户开发",
    "services.leadsDesc": "通过优化的广告渠道开发潜在客户",
    "services.processAutomation": "流程自动化",
    "services.processAutomationDesc": "减轻团队负担并提高转化率",
    "services.crm": "CRM系统",
    "services.crmDesc": "客户管理系统的实施和配置",
    "services.websites": "网站开发",
    "services.websitesDesc": "企业网站、着陆页和在线商店",
    "services.seo": "SEO推广",
    "services.seoDesc": "Yandex和Google搜索引擎优化",
    "services.contextAds": "上下文广告",
    "services.contextAdsDesc": "在Google、Yandex、Meta和社交网络上的广告",
    "services.aiBots": "AI机器人和聊天机器人",
    "services.aiBotsDesc": "用于Telegram、WhatsApp和网站的智能机器人",
    "services.integrations": "系统集成",
    "services.integrationsDesc": "CRM、1C、网站和外部服务之间的连接",

    // Search suggestions
    "search.category": "类别",
    "search.section": "分类",
    "search.company": "公司",
    "search.subcategories": "个子类别",

    // Work hours days
    "days.weekdays": "周一至周五",
    "days.saturday": "周六",
    "days.sunday": "周日",
    "days.dayOff": "休息",
    "days.roundClock": "全天候",
    "days.byAppointment": "预约",

    // Company page UI
    "company.quickActions": "快捷操作",
    "company.locationOnMap": "地图位置",
    "company.buildRoute": "规划路线",
    "company.found": "找到",

    // Filter labels
    "filter.region": "地区",

    // Company data - Company 1 (24pds)
    "company.1.name": "24pds 柴油服务站",
    "company.1.address": "明斯克, 混凝土通道, 19A",
    "company.1.description": "汽车电气维修、燃油泵、悬架和轮胎服务",
    "company.1.about": "柴油服务站是一家拥有多年经验的专业汽车服务中心。我们专门从事柴油发动机维修、燃油设备和汽车电气维修。我们的专家使用现代诊断设备。",
    "company.1.services": "燃油泵维修, 喷油器维修, 发动机诊断, 汽车电气维修, 轮胎服务, 悬架维修",
    "company.1.products": "柴油发动机零件, 燃油喷油器, 滤清器",

    // Company 33 (МедЦентр Плюс)
    "company.33.name": "医疗中心Plus",
    "company.33.address": "明斯克, 苏尔加诺瓦街, 47B",
    "company.33.description": "多学科医疗中心",
    "company.33.about": "医疗中心Plus是明斯克市中心的现代化多学科诊所。由最高级别的医生接诊。拥有自己的实验室和诊断设备。",
    "company.33.services": "内科, 心脏病科, 神经科, 妇科, 泌尿科, 超声波, 实验室检测",

    // Company 45 (IT Solutions)
    "company.45.name": "IT Solutions",
    "company.45.address": "明斯克, 库普列维奇街, 1/1",
    "company.45.description": "软件开发",
    "company.45.about": "IT Solutions是一家软件开发公司。我们创建网络应用程序、移动应用程序、企业系统。",
    "company.45.services": "网站开发, 移动应用, ERP系统, CRM, 技术支持",

    // Companies 2-20 (Auto)
    "company.2.name": "卡车国际服务有限公司",
    "company.2.address": "明斯克区, 普里沃利内村, 和平街, 14/40",
    "company.2.description": "卡车和轿车、牵引车和拖车维修",
    "company.3.name": "PRO-WE汽车中心",
    "company.3.address": "布列斯特区, 切尔尼村, 绿色街, 49",
    "company.3.description": "轿车和卡车3D四轮定位",
    "company.4.name": "空气服务",
    "company.4.address": "明斯克区, 普里沃利内村, 和平街, 12",
    "company.4.description": "卡车和特种车辆维修站",
    "company.5.name": "维斯塔汽车合资公司",
    "company.5.address": "布列斯特, 商业街, 17",
    "company.5.description": "卡车维修、轮胎服务",
    "company.6.name": "汽车大师Plus",
    "company.6.address": "明斯克, 普里季茨科街, 62",
    "company.6.description": "全方位轿车维修服务",
    "company.7.name": "戈梅利专业服务站",
    "company.7.address": "戈梅利, 苏维埃街, 78",
    "company.7.description": "诊断、发动机维修、底盘维修",
    "company.8.name": "欧洲汽车服务",
    "company.8.address": "维捷布斯克, 莫斯科大街, 25",
    "company.8.description": "欧洲汽车专业服务",
    "company.9.name": "YMZ区域中心",
    "company.9.address": "明斯克, 巴布什金街, 21",
    "company.9.description": "YMZ发动机维修、诊断",
    "company.10.name": "格罗德诺汽车服务",
    "company.10.address": "格罗德诺, 高尔基街, 91",
    "company.10.description": "所有品牌汽车综合维修",
    "company.11.name": "莫吉廖夫汽车技术中心",
    "company.11.address": "莫吉廖夫, 切柳斯金街, 45",
    "company.11.description": "车身维修、喷漆、抛光",
    "company.12.name": "白俄柴油服务",
    "company.12.address": "明斯克, 放射街, 15",
    "company.12.description": "柴油发动机和燃油系统维修",
    "company.13.name": "汽车配件",
    "company.13.address": "明斯克, 多尔戈布罗德街, 24",
    "company.13.description": "所有品牌轿车零配件",
    "company.14.name": "卡车零件BEL",
    "company.14.address": "明斯克, 卡津茨街, 86",
    "company.14.description": "MAZ、KAMAZ卡车零配件",
    "company.15.name": "布列斯特汽车世界",
    "company.15.address": "布列斯特, 莫斯科街, 332",
    "company.15.description": "汽车配件批发零售",
    "company.16.name": "戈梅利零件Plus",
    "company.16.address": "戈梅利, 巴里金街, 150",
    "company.16.description": "原装和副厂零配件",
    "company.17.name": "维捷布斯克汽车配件",
    "company.17.address": "维捷布斯克, 建设者大街, 18",
    "company.17.description": "进口车零配件、区域配送",
    "company.18.name": "轮胎服务24",
    "company.18.address": "明斯克, 季米里亚泽夫街, 67",
    "company.18.description": "24小时轮胎服务、轮胎存储",
    "company.19.name": "布列斯特轮胎",
    "company.19.address": "布列斯特, 果戈理街, 78",
    "company.19.description": "轮胎服务、平衡、轮辋维修",
    "company.20.name": "戈梅利轮胎",
    "company.20.address": "戈梅利, 苏维埃街, 136",
    "company.20.description": "各种规格轮胎销售和安装",

    // Companies 21-32 (Construction)
    "company.21.name": "明斯克建筑有限公司",
    "company.21.address": "明斯克, 卡尔瓦里街, 25",
    "company.21.description": "住宅和商业建筑交钥匙工程",
    "company.22.name": "布列斯特建筑",
    "company.22.address": "布列斯特, 列宁街, 45",
    "company.22.description": "各种复杂程度的建筑工程",
    "company.23.name": "戈梅利住宅建筑",
    "company.23.address": "戈梅利, 列宁大街, 55",
    "company.23.description": "多户住宅建设",
    "company.24.name": "维捷布斯克建筑",
    "company.24.address": "维捷布斯克, 城堡街, 20",
    "company.24.description": "建筑总承包商",
    "company.25.name": "格罗德诺工业建筑",
    "company.25.address": "格罗德诺, 苏维埃街, 18",
    "company.25.description": "工业和民用建筑",
    "company.26.name": "莫吉廖夫建筑投资",
    "company.26.address": "莫吉廖夫, 五一街, 75",
    "company.26.description": "投资建设",
    "company.27.name": "建材BEL",
    "company.27.address": "明斯克, 卡津茨街, 120",
    "company.27.description": "建筑材料批发",
    "company.28.name": "布列斯特陶瓷",
    "company.28.address": "布列斯特, 莫斯科街, 275",
    "company.28.description": "瓷砖、卫浴设备",
    "company.29.name": "戈梅利建材基地",
    "company.29.address": "戈梅利, 巴里金街, 200",
    "company.29.description": "建筑和装修所需一切材料",
    "company.30.name": "装修Plus",
    "company.30.address": "明斯克, 苏尔加诺瓦街, 57A",
    "company.30.description": "公寓交钥匙装修",
    "company.31.name": "戈梅利装修",
    "company.31.address": "戈梅利, 列宁大街, 100",
    "company.31.description": "公寓和办公室装修",
    "company.32.name": "维捷布斯克欧式装修",
    "company.32.address": "维捷布斯克, 列宁街, 45",
    "company.32.description": "各种复杂程度的优质装修",

    // Companies 34-44 (Medicine)
    "company.34.name": "洛德诊所",
    "company.34.address": "明斯克, 普里季茨科街, 140",
    "company.34.description": "私人医疗诊所",
    "company.35.name": "布列斯特医疗中心",
    "company.35.address": "布列斯特, 苏维埃街, 67",
    "company.35.description": "诊断和治疗",
    "company.36.name": "戈梅利医疗",
    "company.36.address": "戈梅利, 苏维埃街, 45",
    "company.36.description": "现代医疗中心",
    "company.37.name": "维捷布斯克医疗中心",
    "company.37.address": "维捷布斯克, 伏龙芝大街, 80",
    "company.37.description": "广泛的医疗服务",
    "company.38.name": "32号牙科",
    "company.38.address": "明斯克, 涅米加街, 38",
    "company.38.description": "现代牙科诊所",
    "company.39.name": "牙科维塔",
    "company.39.address": "明斯克, 斯克里加诺瓦街, 14",
    "company.39.description": "种植、假牙、治疗",
    "company.40.name": "微笑牙科",
    "company.40.address": "维捷布斯克, 城堡街, 12",
    "company.40.description": "全家牙科服务",
    "company.41.name": "布列斯特牙科",
    "company.41.address": "布列斯特, 果戈理街, 55",
    "company.41.description": "治疗、假牙、正畸",
    "company.42.name": "急救药房",
    "company.42.address": "明斯克, 独立大街, 58",
    "company.42.description": "丰富的药品种类",
    "company.43.name": "健康药房",
    "company.43.address": "格罗德诺, 苏维埃街, 5",
    "company.43.description": "药品和医疗用品",
    "company.44.name": "戈梅利药房",
    "company.44.address": "戈梅利, 苏维埃街, 97",
    "company.44.description": "送药上门药房",

    // Companies 46-55 (IT, Trade)
    "company.46.name": "格罗德诺网站开发",
    "company.46.address": "格罗德诺, 高尔基街, 87",
    "company.46.description": "网站和网络应用开发",
    "company.47.name": "明斯克软件",
    "company.47.address": "明斯克, 季米里亚泽夫街, 72",
    "company.47.description": "移动应用开发",
    "company.48.name": "布列斯特IT服务",
    "company.48.address": "布列斯特, 苏维埃街, 100",
    "company.48.description": "电脑和笔记本维修",
    "company.49.name": "电脑大师",
    "company.49.address": "明斯克, 涅米加街, 12",
    "company.49.description": "紧急设备维修",
    "company.50.name": "电器世界",
    "company.50.address": "明斯克, 独立大街, 150",
    "company.50.description": "家用电器和电子产品",
    "company.51.name": "科技Plus",
    "company.51.address": "戈梅利, 苏维埃街, 1",
    "company.51.description": "电脑、手机、配件",
    "company.52.name": "家具之家",
    "company.52.address": "莫吉廖夫, 五一街, 25",
    "company.52.description": "家庭和办公家具",
    "company.53.name": "家具城",
    "company.53.address": "明斯克, 乌鲁奇街, 19",
    "company.53.description": "白俄罗斯制造商家具",
    "company.54.name": "时尚与风格",
    "company.54.address": "明斯克, 涅米加街, 3",
    "company.54.description": "品牌服装和鞋类",
    "company.55.name": "布列斯特服装",
    "company.55.address": "布列斯特, 苏维埃街, 65",
    "company.55.description": "全家服装",

    // Companies 56-77 (Restaurants, Beauty, Services, Transport, Real Estate)
    "company.56.name": "明斯克餐厅",
    "company.56.address": "明斯克, 胜利者大街, 17",
    "company.56.description": "白俄罗斯和欧洲美食",
    "company.57.name": "卡米亚尼察",
    "company.57.address": "明斯克, 自由广场, 3",
    "company.57.description": "传统白俄罗斯美食",
    "company.58.name": "布列斯特餐厅",
    "company.58.address": "布列斯特, 苏维埃街, 49",
    "company.58.description": "欧洲美食、宴会",
    "company.59.name": "舒适咖啡馆",
    "company.59.address": "布列斯特, 苏维埃街, 50",
    "company.59.description": "温馨家常菜咖啡馆",
    "company.60.name": "戈梅利咖啡馆",
    "company.60.address": "戈梅利, 列宁大街, 18",
    "company.60.description": "咖啡、甜点、早餐",
    "company.61.name": "意大利披萨店",
    "company.61.address": "明斯克, 苏尔加诺瓦街, 27",
    "company.61.description": "意大利披萨、外卖",
    "company.62.name": "美学美容院",
    "company.62.address": "明斯克, 涅米加街, 40",
    "company.62.description": "全方位美容服务",
    "company.63.name": "Bravo美容工作室",
    "company.63.address": "明斯克, 普里季茨科街, 83",
    "company.63.description": "美甲、修脚、美发",
    "company.64.name": "维多利亚沙龙",
    "company.64.address": "布列斯特, 苏维埃街, 78",
    "company.64.description": "理发、染发、护理",
    "company.65.name": "能量健身俱乐部",
    "company.65.address": "明斯克, 普里季茨科街, 156",
    "company.65.description": "健身房、团体课程",
    "company.66.name": "放松水疗中心",
    "company.66.address": "明斯克, 苏尔加诺瓦街, 5A",
    "company.66.description": "按摩、桑拿、美容",
    "company.67.name": "TOPGUN理发店",
    "company.67.address": "明斯克, 齐比茨卡街, 6",
    "company.67.description": "男士理发和胡须护理",
    "company.68.name": "法律公司",
    "company.68.address": "明斯克, 独立大街, 72",
    "company.68.description": "法律咨询和代理",
    "company.69.name": "布列斯特律师事务所",
    "company.69.address": "布列斯特, 列宁街, 31",
    "company.69.description": "律师服务",
    "company.70.name": "会计服务",
    "company.70.address": "明斯克, 托尔布欣街, 2",
    "company.70.description": "企业会计服务",
    "company.71.name": "专业清洁",
    "company.71.address": "明斯克, 卡津茨街, 52",
    "company.71.description": "公寓、办公室、别墅清洁",
    "company.72.name": "白俄货运",
    "company.72.address": "明斯克, 放射街, 40A",
    "company.72.description": "白俄罗斯和独联体货运",
    "company.73.name": "明斯克出租车135",
    "company.73.address": "明斯克",
    "company.73.description": "明斯克及周边地区出租车",
    "company.74.name": "汽车租赁",
    "company.74.address": "明斯克, 普里季茨科街, 60",
    "company.74.description": "无司机汽车租赁",
    "company.75.name": "你的家房产中介",
    "company.75.address": "明斯克, 独立大街, 95",
    "company.75.description": "房产买卖、租赁",
    "company.76.name": "A-100开发",
    "company.76.address": "明斯克, 基洛夫街, 8",
    "company.76.description": "住宅小区建设",
    "company.77.name": "办公室租赁BC",
    "company.77.address": "明斯克, 苏尔加诺瓦街, 61",
    "company.77.description": "商业房地产",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ru");
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
    if (stored && ["ru", "en", "be", "zh"].includes(stored)) {
      setLanguageState(stored);
    }
    setIsInitialized(true);
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem(LANGUAGE_STORAGE_KEY, lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language][key] || translations.ru[key] || key;
    },
    [language]
  );

  if (!isInitialized) {
    return null;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
