export const IBIZ_CATEGORY_ICONS: Record<string, string> = {
  "avtomobilnaya-tehnika-uslugi-transport": "🚗",
  "apk-selskoe-i-lesnoe-hozyaystvo": "🌾",
  "banki-birji-finansy": "💰",
  "biznes-uslugi-dlya-biznesa": "💼",
  "derevoobrabotka-i-mebel": "🪵",
  "dom-i-byt-bytovye-uslugi": "🏠",
  "gosudarstvo-i-obshchestvo": "🏛️",
  "himiya-energetika-syre": "⚡",
  "iskusstvo-suveniry-yuvelirnye-izdeliya": "🎁",
  "it-internet-i-orgtehnika": "💻",
  "legkaya-promyshlennost": "🧵",
  "mashinostroenie-i-oborudovanie": "⚙️",
  "medicina-i-farmacevtika": "🏥",
  "metally-metalloobrabotka": "🧲",
  "nedvizhimost": "🏠",
  "obrazovanie-nauka-karera": "🎓",
  "poligrafiya-izdatelstvo-upakovka": "🖨️",
  "promyshlennost-pishchevaya": "🍽️",
  "reklamnaya-deyatelnost-smi": "📣",
  "sport-zdorove-krasota": "💅",
  "stroitelstvo-nedvijimost": "🏗️",
  "strojmateriali-otdelochnie-materiali": "🧱",
  "telekommunikatsii-i-svyaz": "📡",
  "torgovlya-logistika": "🛒",
  "transport-logistika-perevozki": "🚚",
  "turizm-otdyh-dosug": "🧳",
  "uslugi-dlya-naseleniya": "🔧",
};

